import { useState, useEffect, useCallback, useRef } from 'react';
import { useQueryClient } from '@tanstack/react-query';
import { useAuthStore } from '@/features/auth/store/useAuthStore';
import progressService from '../../services/progressService';
import apiService from '@/features/auth/services/apiClient';
import type { StudyStats, CourseProgressData, UnitProgressData } from '@/shared/types/progressInterface';
import type { 
  StudySessionInternal, 
  StudySession, 
  StudySessionActivity,
  StudySessionContext,
  StudyResumePoint,
  CourseProgressResponse, 
  UnitProgressResponse,
} from '@/shared/types/studyInterface';

interface StudyPeriodSummary {
  totalSessions: number;
  totalHours: number;
  avgSessionLength: number;
  avgFocusScore: number;
}

export const useStudy = () => {
  const { user } = useAuthStore();
  const queryClient = useQueryClient();
  const [sessions, setSessions] = useState<StudySessionInternal[]>([]);
  const [stats, setStats] = useState<StudyStats>({
    totalSessions: 0,
    totalTime: 0,
    averageScore: 0,
    currentStreak: 0,
    topicsStudied: [],
    courseProgress: [],
    unitProgress: [],
  });
  const [isLoading, setIsLoading] = useState(false);
  
  const statsRef = useRef(stats);
  useEffect(() => {
    statsRef.current = stats;
  }, [stats]);

  const startSession = useCallback(async (
    context?: StudySessionContext | string,
    contextType: StudySessionContext['type'] = 'topic'
  ): Promise<StudySessionInternal | null> => {
    if (!user?.id) return null;
    
    try {
      const sessionContext = typeof context === 'string'
        ? { type: contextType, id: context }
        : context;
      const payload = sessionContext ? { context: sessionContext } : {};

      const response = await apiService.post<StudySession>('/study/session/start', payload);
      const session = response.data;
      
      // Transform if necessary, backend returns proper StudySession shape
      // Frontend StudySessionInternal might need adaptation if types differ
      const sessionInternal: StudySessionInternal = {
          id: session.id,
          startTime: new Date(session.startTime),
          endTime: session.endTime ? new Date(session.endTime) : undefined,
          userId: session.userId,
          duration: session.duration ?? 0,
          topic: session.topicId || sessionContext?.id || ''
      };

      setSessions(prev => [...prev, sessionInternal]);
      return sessionInternal;
    } catch (error) {
      console.error('Failed to start study session:', error);
      return null;
    }
  }, [user?.id]);

  const endSession = useCallback(async (
    sessionId: string,
    notes?: string,
    activities: StudySessionActivity[] = [],
    durationSeconds?: number,
  ): Promise<StudySession> => {
    try {
        const response = await apiService.put<StudySession>(`/study/session/${sessionId}/end`, {
            activities,
            notes,
            durationSeconds,
        });
        const endedSession = response.data;

        // Update local state
        setSessions(prev =>
            prev.map(session =>
              session.id === sessionId
                ? {
                    ...session,
                    endTime: endedSession.endTime
                      ? new Date(endedSession.endTime)
                      : new Date(),
                    duration: endedSession.duration ?? (durationSeconds !== undefined
                      ? durationSeconds / 60
                      : session.startTime
                        ? (Date.now() - new Date(session.startTime).getTime()) / 1000 / 60
                        : 0),
                    notes: endedSession.notes ?? notes,
                  }
                : session
            )
          );
        if (user?.id) {
          await Promise.all([
            queryClient.invalidateQueries({ queryKey: ['userProgress', user.id] }),
            queryClient.invalidateQueries({ queryKey: ['userLearningStreak', user.id] }),
            queryClient.invalidateQueries({ queryKey: ['studyPlanner', user.id] }),
            queryClient.invalidateQueries({ queryKey: ['course-progress-dashboard', user.id] }),
            queryClient.invalidateQueries({ queryKey: ['courseStatistics', user.id] }),
            queryClient.invalidateQueries({ queryKey: ['dashboardAssessmentSummary', user.id] }),
            queryClient.invalidateQueries({ queryKey: ['autoGeneratedQuizzes', user.id] }),
            queryClient.invalidateQueries({ queryKey: ['studyResume', user.id] }),
            queryClient.invalidateQueries({ queryKey: ['courses'] }),
            queryClient.invalidateQueries({ queryKey: ['unit'] }),
          ]);
        }
        return endedSession;
    } catch (error) {
        console.error('Failed to end study session:', error);
      throw error;
    }
  }, [queryClient, user?.id]);

  const getStudyStats = useCallback(async (): Promise<StudyStats> => {
    if (!user?.id) return statsRef.current;
    
    try {
      setIsLoading(true);
      const [summaryResponse, streakData] = await Promise.all([
        apiService.get<StudyPeriodSummary>('/study/data/summary?period=week'),
        progressService.getUserStreaks(user.id),
      ]);

      const currentStats = statsRef.current;

      const updatedStats: StudyStats = {
        totalSessions: summaryResponse.data.totalSessions,
        totalTime: Math.round(summaryResponse.data.totalHours * 60),
        averageScore: currentStats.averageScore,
        currentStreak: streakData.currentStreak,
        topicsStudied: currentStats.topicsStudied, // Need separate endpoint for detailed topics if not in overview
        courseProgress: currentStats.courseProgress, 
        unitProgress: currentStats.unitProgress,
      };

      setStats(updatedStats);
      return updatedStats;
    } catch (error) {
      console.error('Error fetching study stats:', error);
      throw error;
    } finally {
      setIsLoading(false);
    }
  }, [user?.id]);
  
  // Fetch real course progress
  const getCourseProgress = useCallback(async (): Promise<CourseProgressData[]> => {
    if (!user?.id) return [];
    try {
      const response = await progressService.getCourseProgress(user.id);
      // Map response to CourseProgressData
      const mapped = response.map((c: CourseProgressResponse) => ({
          id: c.courseId || c.id || '',
          name: c.course?.title || c.title || 'Untitled',
          progressPercentage: c.progressPercentage || 0,
          lastUpdated: c.lastAccessedAt ? Date.parse(c.lastAccessedAt) : undefined,
      }));
      setStats(prev => ({ ...prev, courseProgress: mapped }));
      return mapped;
    } catch (e) {
      console.error('Failed to load course progress:', e);
      throw e;
    }
  }, [user?.id]);

  const getUnitProgress = useCallback(async (courseId?: string): Promise<UnitProgressData[]> => {
      if (!user?.id) return [];
      try {
          const response = await progressService.getUnitProgress(user.id, courseId);
          const mapped = response.map((u: UnitProgressResponse) => ({
              id: u.unitId || u.id || '',
              name: u.unit?.title || u.unitTitle || u.title || 'Untitled',
              courseId: u.unit?.courseId || courseId || '',
              progressPercentage: u.progressPercentage || 0,
              lastUpdated: u.lastAccessedAt ? Date.parse(u.lastAccessedAt) : undefined,
          }));
          setStats(prev => ({ ...prev, unitProgress: mapped }));
          return mapped;
      } catch (e) {
          console.error('Failed to load unit progress:', e);
          throw e;
      }
  }, [user?.id]);

  const getResumePoint = useCallback(async (courseId: string) => {
    if (!user?.id) {
      throw new Error('User is not authenticated.');
    }
    return queryClient.fetchQuery({
      queryKey: ['studyResume', user.id, courseId],
      queryFn: async () => {
        const res = await apiService.get<StudyResumePoint>(`/study/resume/${courseId}`);
        return res.data;
      },
      staleTime: 30 * 1000,
      gcTime: 10 * 60 * 1000,
    });
  }, [queryClient, user?.id]);

  return {
    sessions,
    stats,
    isLoading,
    startSession,
    endSession,
    getStudyStats,
    getCourseProgress,
    getUnitProgress,
    getResumePoint
  };
};
