ignoredBuiltDependencies:
  - '@swc/core'
  - aws-sdk
  - unrs-resolver

overrides:
  "hono@*": "4.10.3"
  "glob@^10": "10.5.0"
  "glob@^11": "11.1.0"
  "js-yaml@^3": "3.14.2"
  "js-yaml@^4": "4.1.1"
  "body-parser@>=2.2.0 <2.2.1": ">=2.2.1"
  "jws@<3.2.3": ">=3.2.3"
  "hono@<4.11.4": ">=4.11.4"
  "lodash@>=4.0.0 <=4.17.22": ">=4.17.23"
  "hono@<4.11.7": ">=4.11.7"
  "tar@<7.5.7": ">=7.5.7"
  "diff@>=4.0.0 <4.0.4": ">=4.0.4"
  "validator@<13.15.22": ">=13.15.22"
  "@isaacs/brace-expansion@<=5.0.0": ">=5.0.1"
  "webpack@>=5.49.0 <=5.104.0": ">=5.104.1"
  "webpack@>=5.49.0 <5.104.0": ">=5.104.0"
  "fast-xml-parser@>=5.0.9 <=5.3.3": ">=5.3.4"
  "qs@>=6.7.0 <=6.14.1": ">=6.14.2"
  "axios@>=1.0.0 <=1.13.4": ">=1.13.5"
  "tar@<=7.5.2": ">=7.5.3"
  "hono@<4.11.10": ">=4.11.10"
  "tar@<7.5.8": ">=7.5.8"
  "minimatch@<3.1.3": ">=3.1.3"
  "minimatch@>=9.0.0 <9.0.6": ">=9.0.6"
  "minimatch@>=10.0.0 <10.2.1": ">=10.2.1"
  "minimatch@>=9.0.0 <9.0.7": ">=9.0.7"
  "minimatch@>=10.0.0 <10.2.3": ">=10.2.3"
  "minimatch@<3.1.4": ">=3.1.4"
  "minimatch@*": ">=10.2.3"
  "fast-xml-parser@>=5.0.0 <5.3.5": ">=5.3.5"
  "fast-xml-parser@>=5.0.0 <5.3.6": ">=5.3.6"
  "multer@<2.1.0": ">=2.1.0"
  "serialize-javascript@<=7.0.2": ">=7.0.3"
  "ajv@<6.14.0": ">=6.14.0"
  "ajv@>=7.0.0-alpha.0 <8.18.0": ">=8.18.0"
  "qs@<6.14.1": ">=6.14.1"
  "multer@<2.1.1": ">=2.1.1"
  "hono@<4.12.4": ">=4.12.4"
  "fast-xml-parser@>=5.0.0 <5.3.8": ">=5.3.8"
  "@hono/node-server@<1.19.10": ">=1.19.10"
  "tar@<=7.5.9": ">=7.5.10"
  "file-type@>=13.0.0 <21.3.1": ">=21.3.1"
  "tar@<=7.5.10": ">=7.5.11"
  "hono@<4.12.7": ">=4.12.7"
  "flatted@<3.4.0": ">=3.4.0"
  "yauzl@=3.2.0": ">=3.2.1"
  "tar@<=7.5.3": ">=7.5.4"
  "file-type@>=20.0.0 <=21.3.1": ">=21.3.2"
  "fast-xml-parser@>=4.0.0-beta.3 <=5.5.5": ">=5.5.6"

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - argon2
  - grpc-tools
  - msgpackr-extract
  - prisma
  - protobufjs
