const { PrismaClient } = require('@prisma/client');
const { PrismaPg } = require('@prisma/adapter-pg');
const { Pool } = require('pg');
const dotenv = require('dotenv');

dotenv.config();

async function run() {
  const _pool = new Pool({ connectionString: process.env.DATABASE_URL });
  const _adapter = new PrismaPg(_pool);
  const prisma = new PrismaClient({ adapter: _adapter });

  try {
    const autoQuizzes = await prisma.autoGeneratedQuiz.findMany();
    console.log('AUTO_QUIZZES:', JSON.stringify(autoQuizzes, null, 2));

    const allQuizzes = await prisma.quiz.findMany({
      take: 10,
      orderBy: { createdAt: 'desc' }
    });
    console.log('RECENT QUIZZES:', JSON.stringify(allQuizzes, null, 2));

  } catch (e) {
    console.error(e);
  } finally {
    await prisma.$disconnect();
    await _pool.end();
  }
}

run();
