import React, { useState, useEffect } from 'react';
import ProgressBar from '@/shared/components/ui/ProgressBar';
import { useStudy } from '@/features/learning-management/study/hooks/useStudy';
import { usePeerBenchmarking } from '@/features/analytics/hooks/usePeerBenchmarking';
import { AutoGeneratedQuizCard } from '@/features/assessment/components/auto-generated-quiz-card';
import type { StudyStats } from '@/shared/types/progressInterface';
import { GoalsProgressWidget } from '@/features/learning-management/components/goals/goals-progress-widget';

// Minimal local types to avoid using `any` and keep this component focused
type CourseProgress = { id: string; name: string; progressPercentage: number; lastUpdated?: number };
type UnitProgress = { id: string; name: string; courseId: string; progressPercentage: number; lastUpdated?: number };
type PeerStats = { userPercentile: number; averageScore: number; userScore: number };
type AutoGeneratedQuiz = {
  id: string;
  quizId: string;
  quizTitle: string;
  weaknessTopicId: string;
  weaknessTopicName: string;
  riskLevel: 'HIGH' | 'MEDIUM' | 'LOW';
  detectedAt: string;
};

export const StudyDashboard: React.FC = () => {
  const { getStudyStats, getCourseProgress, getUnitProgress } = useStudy();
  const { getPeerStats } = usePeerBenchmarking();

  const [stats, setStats] = useState<StudyStats | null>(null);
  const [courseProgress, setCourseProgress] = useState<CourseProgress[]>([]);
  const [unitProgress, setUnitProgress] = useState<UnitProgress[]>([]);
  const [peerStats, setPeerStats] = useState<PeerStats | null>(null);
  const [autoQuizzes, setAutoQuizzes] = useState<AutoGeneratedQuiz[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const loadDashboard = async () => {
      try {
        const [statsData, courseData, unitData] = await Promise.all([
          getStudyStats(),
          getCourseProgress(),
          getUnitProgress(),
        ]);
        setStats(statsData);
        setCourseProgress(courseData);
        setUnitProgress(unitData);

        const peerData = await getPeerStats();
        setPeerStats(peerData);

        // Fetch auto-generated quizzes from API
        try {
          const response = await fetch('/api/assessments/auto-generated-quizzes');
          if (response.ok) {
            const data = await response.json();
            setAutoQuizzes(data.data || []);
          }
        } catch (error) {
          console.error('Error fetching auto-generated quizzes:', error);
        }
      } catch (error) {
        console.error('Error loading dashboard:', error);
      } finally {
        setLoading(false);
      }
    };

    loadDashboard();
  }, [getStudyStats, getCourseProgress, getUnitProgress, getPeerStats]);

  if (loading) {
    return (
      <div className="flex justify-center items-center min-h-[60vh]">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500 mx-auto mb-4" />
        <p className="text-gray-600 dark:text-slate-400">Loading...</p>
      </div>
    );
  }

  // Format lastUpdated timestamp for display
  const formatLastUpdated = (timestamp?: number): string => {
    if (!timestamp) return 'Not synced';
    const now = Date.now();
    const diffMs = now - timestamp;
    const diffMins = Math.floor(diffMs / 60000);
    if (diffMins < 1) return 'Just now';
    if (diffMins < 60) return `${diffMins}m ago`;
    const diffHours = Math.floor(diffMins / 60);
    if (diffHours < 24) return `${diffHours}h ago`;
    const diffDays = Math.floor(diffHours / 24);
    return `${diffDays}d ago`;
  };

  return (
    <div className="p-3 bg-gray-50/50 dark:bg-slate-900/50 min-h-screen">
      {/* AI-Generated Practice Quizzes */}
      {autoQuizzes.length > 0 && (
        <div className="mb-6">
          <h5 className="text-lg font-semibold mb-3 text-gray-900 dark:text-white flex items-center gap-2">
            <span>✨</span>
            AI-Generated Practice Quizzes
          </h5>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
            {autoQuizzes.map(quiz => (
              <AutoGeneratedQuizCard
                key={quiz.id}
                quizId={quiz.quizId}
                weaknessTopicName={quiz.weaknessTopicName}
                oldMastery={0.5}
                riskLevel={quiz.riskLevel}
                detectedAt={new Date(quiz.detectedAt)}
                onDismiss={() => {
                  setAutoQuizzes(autoQuizzes.filter(q => q.id !== quiz.id));
                }}
              />
            ))}
          </div>
        </div>
      )}

      {/* Stats Overview */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mb-4">
        <div className="bg-white/80 dark:bg-slate-800/50 backdrop-blur-sm rounded-lg shadow-sm border border-gray-100 dark:border-slate-700/50 p-4">
          <h6 className="text-lg font-semibold mb-2 text-gray-900 dark:text-white">Total Study Time</h6>
          <p className="text-4xl font-bold text-blue-600 dark:text-blue-400">
            {Math.round((stats?.totalTime || 0) / 60)}h
          </p>
          <p className="text-sm text-gray-500 dark:text-slate-400">this week</p>
        </div>
        <div className="bg-white/80 dark:bg-slate-800/50 backdrop-blur-sm rounded-lg shadow-sm border border-gray-100 dark:border-slate-700/50 p-4">
          <h6 className="text-lg font-semibold mb-2 text-gray-900 dark:text-white">Study Sessions</h6>
          <p className="text-4xl font-bold text-blue-600 dark:text-blue-400">{stats?.totalSessions || 0}</p>
          <p className="text-sm text-gray-500 dark:text-slate-400">completed</p>
        </div>
      </div>

      {/* Course Progress */}
      <div className="bg-white/80 dark:bg-slate-800/50 backdrop-blur-sm rounded-lg shadow-sm border border-gray-100 dark:border-slate-700/50 p-4 mb-4">
        <h6 className="text-lg font-semibold mb-2 text-gray-900 dark:text-white">Course Progress</h6>
        {courseProgress.map(course => (
          <div key={course.id} className="mb-3">
            <div className="flex justify-between mb-1">
              <p className="text-base text-gray-900 dark:text-slate-200">{course.name}</p>
              <p className="text-sm text-gray-500 dark:text-slate-400">{course.progressPercentage}%</p>
            </div>
            <div className="w-full h-2">
              <ProgressBar value={course.progressPercentage} className="h-2 rounded-full" />
            </div>
            <p className="text-xs text-gray-400 dark:text-slate-500 mt-1">
              Last synced: {formatLastUpdated(course.lastUpdated)}
            </p>
          </div>
        ))}
      </div>

      {/* Unit Progress */}
      <div className="bg-white/80 dark:bg-slate-800/50 backdrop-blur-sm rounded-lg shadow-sm border border-gray-100 dark:border-slate-700/50 p-4 mb-4">
        <h6 className="text-lg font-semibold mb-2 text-gray-900 dark:text-white">Unit Progress</h6>
        {unitProgress.map(unit => (
          <div key={unit.id} className="mb-3">
            <div className="flex justify-between mb-1">
              <p className="text-base text-gray-900 dark:text-slate-200">
                {unit.name} ({courseProgress.find(c => c.id === unit.courseId)?.name})
              </p>
              <p className="text-sm text-gray-500 dark:text-slate-400">{unit.progressPercentage}%</p>
            </div>
            <div className="w-full h-2">
              <ProgressBar value={unit.progressPercentage} className="h-2 rounded-full" />
            </div>
            <p className="text-xs text-gray-400 dark:text-slate-500 mt-1">
              Last synced: {formatLastUpdated(unit.lastUpdated)}
            </p>
          </div>
        ))}
      </div>

      {/* Peer Comparison */}
      <div className="bg-white/80 dark:bg-slate-800/50 backdrop-blur-sm rounded-lg shadow-sm border border-gray-100 dark:border-slate-700/50 p-4">
        <h6 className="text-lg font-semibold mb-2 text-gray-900 dark:text-white">Peer Comparison</h6>
        {peerStats && (
          <div>
            <p className="text-sm text-gray-500 dark:text-slate-400 mb-2">
              You're in the top {Math.round(peerStats.userPercentile)}%
            </p>
            <div className="mt-2">
              <p className="text-sm text-gray-600 dark:text-slate-300">
                Average Completion: {Math.round(peerStats.averageScore)}%
              </p>
              <p className="text-sm text-gray-600 dark:text-slate-300">
                Your Completion: {Math.round(peerStats.userScore)}%
              </p>
            </div>
          </div>
        )}
      </div>

      {/* Goals Integration */}
      <div className="mt-4">
        <GoalsProgressWidget />
      </div>
    </div>
  );
};
