import React from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useRouter } from 'next/navigation';
import ProgressBar from '@/shared/components/ui/ProgressBar';
import { useStudy } from '@/features/learning-management/study/hooks/useStudy';
import { AutoGeneratedQuizCard } from '@/features/assessment/components/auto-generated-quiz-card';
import type { StudyStats } from '@/shared/types/progressInterface';
import { GoalsProgressWidget } from '@/features/learning-management/components/goals/goals-progress-widget';
import { useAuthStore } from '@/features/auth/store/useAuthStore';
import { useProgress } from '@/shared/hooks/useProgress';
import apiService from '@/features/auth/services/apiClient';

// Minimal local types to avoid using `any` and keep this component focused
type CourseProgress = { id: string; name: string; progressPercentage: number; lastUpdated?: number };
type UnitProgress = { id: string; name: string; courseId: string; progressPercentage: number; lastUpdated?: number };
type PeerStats = { userPercentile: number; averageScore: number; userScore: number };
type AutoGeneratedQuiz = {
  id: string;
  quizId: string;
  quizTitle: string;
  weaknessTopicId: string;
  weaknessTopicName: string;
  riskLevel: 'HIGH' | 'MEDIUM' | 'LOW';
  detectedAt: string;
  oldMastery?: number;
};

interface StudyPlannerData {
  stats: StudyStats;
  courseProgress: CourseProgress[];
  unitProgress: UnitProgress[];
}

export const StudyDashboard: React.FC = () => {
  const { getStudyStats, getCourseProgress, getUnitProgress } = useStudy();
  const router = useRouter();
  const queryClient = useQueryClient();
  const userId = useAuthStore(state => state.user?.id);
  const { progressData } = useProgress();
  const {
    data: dashboard,
    isLoading,
    isError,
    error,
    refetch,
  } = useQuery<StudyPlannerData>({
    queryKey: ['studyPlanner', userId],
    queryFn: async () => {
      if (!userId) throw new Error('User is not authenticated.');
      const [stats, courseProgress, unitProgress] = await Promise.all([
        getStudyStats(),
        getCourseProgress(),
        getUnitProgress(),
      ]);
      return { stats, courseProgress, unitProgress };
    },
    enabled: Boolean(userId),
    staleTime: 2 * 60 * 1000,
    gcTime: 10 * 60 * 1000,
    meta: { persist: Boolean(userId) },
  });
  const {
    data: autoQuizzes = [],
    isError: autoQuizzesError,
  } = useQuery<AutoGeneratedQuiz[]>({
    queryKey: ['autoGeneratedQuizzes', userId],
    queryFn: async () => {
      const response = await apiService.get<{ data: AutoGeneratedQuiz[] }>(
        '/quizzes/assessments/auto-generated-quizzes',
      );
      return response.data.data;
    },
    enabled: Boolean(userId),
    staleTime: 5 * 60 * 1000,
    gcTime: 10 * 60 * 1000,
    meta: { persist: Boolean(userId) },
  });
  const stats = dashboard?.stats;
  const courseProgress = dashboard?.courseProgress ?? [];
  const unitProgress = dashboard?.unitProgress ?? [];
  const peerComparison = progressData?.peerComparison;
  const peerStats: PeerStats | null = peerComparison
    ? {
        userPercentile: peerComparison.totalStudents > 0
          ? Math.max(0, Math.round((1 - peerComparison.rank / peerComparison.totalStudents) * 100))
          : 0,
        averageScore: peerComparison.cohortAverage,
        userScore: peerComparison.yourAverage,
      }
    : null;

  if (isLoading) {
    return (
      <div className="min-h-[60vh] space-y-4" aria-label="Loading study planner">
        <div className="grid gap-4 md:grid-cols-2">
          <div className="h-32 animate-pulse rounded-xl bg-slate-200 dark:bg-slate-800" />
          <div className="h-32 animate-pulse rounded-xl bg-slate-200 dark:bg-slate-800" />
        </div>
        <div className="h-48 animate-pulse rounded-xl bg-slate-200 dark:bg-slate-800" />
        <div className="h-48 animate-pulse rounded-xl bg-slate-200 dark:bg-slate-800" />
      </div>
    );
  }

  if (isError) {
    return (
      <div role="alert" className="rounded-2xl border border-red-200 bg-white p-8 text-center dark:border-red-900 dark:bg-slate-900">
        <h2 className="text-lg font-semibold text-slate-900 dark:text-white">Study data is unavailable</h2>
        <p className="mt-2 text-sm text-slate-600 dark:text-slate-400">
          {error instanceof Error ? error.message : 'We could not load your study progress.'}
        </p>
        <button
          type="button"
          onClick={() => void refetch()}
          className="mt-4 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white hover:bg-indigo-700"
        >
          Try again
        </button>
      </div>
    );
  }

  // Format lastUpdated timestamp for display
  const formatLastUpdated = (timestamp?: number): string => {
    if (!timestamp) return 'Not synced';
    const now = Date.now();
    const diffMs = now - timestamp;
    const diffMins = Math.floor(diffMs / 60000);
    if (diffMins < 1) return 'Just now';
    if (diffMins < 60) return `${diffMins}m ago`;
    const diffHours = Math.floor(diffMins / 60);
    if (diffHours < 24) return `${diffHours}h ago`;
    const diffDays = Math.floor(diffHours / 24);
    return `${diffDays}d ago`;
  };

  return (
    <div className="p-3 bg-gray-50/50 dark:bg-slate-900/50 min-h-screen">
      {/* AI-Generated Practice Quizzes */}
      {autoQuizzesError && (
        <p role="status" className="mb-4 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800 dark:border-amber-900 dark:bg-amber-950/30 dark:text-amber-200">
          Personalized practice quizzes are temporarily unavailable. Your study progress is still up to date.
        </p>
      )}
      {autoQuizzes.length > 0 && (
        <div className="mb-6">
          <h5 className="text-lg font-semibold mb-3 text-gray-900 dark:text-white flex items-center gap-2">
            <span>✨</span>
            AI-Generated Practice Quizzes
          </h5>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3">
            {autoQuizzes.map(quiz => (
              <AutoGeneratedQuizCard
                key={quiz.id}
                quizId={quiz.quizId}
                weaknessTopicName={quiz.weaknessTopicName}
                oldMastery={quiz.oldMastery}
                riskLevel={quiz.riskLevel}
                detectedAt={new Date(quiz.detectedAt)}
                onDismiss={() => {
                  queryClient.setQueryData<AutoGeneratedQuiz[]>(
                    ['autoGeneratedQuizzes', userId],
                    current => current?.filter(item => item.id !== quiz.id),
                  );
                }}
              />
            ))}
          </div>
        </div>
      )}

      {/* Stats Overview */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-3 mb-4">
        <div className="bg-white/80 dark:bg-slate-800/50 backdrop-blur-sm rounded-lg shadow-sm border border-gray-100 dark:border-slate-700/50 p-4">
          <h6 className="text-lg font-semibold mb-2 text-gray-900 dark:text-white">Total Study Time</h6>
          <p className="text-4xl font-bold text-blue-600 dark:text-blue-400">
            {Math.round((stats?.totalTime || 0) / 60)}h
          </p>
          <p className="text-sm text-gray-500 dark:text-slate-400">this week</p>
        </div>
        <div className="bg-white/80 dark:bg-slate-800/50 backdrop-blur-sm rounded-lg shadow-sm border border-gray-100 dark:border-slate-700/50 p-4">
          <h6 className="text-lg font-semibold mb-2 text-gray-900 dark:text-white">Study Sessions</h6>
          <p className="text-4xl font-bold text-blue-600 dark:text-blue-400">{stats?.totalSessions || 0}</p>
          <p className="text-sm text-gray-500 dark:text-slate-400">completed</p>
        </div>
      </div>

      {/* Course Progress */}
      <div className="bg-white/80 dark:bg-slate-800/50 backdrop-blur-sm rounded-lg shadow-sm border border-gray-100 dark:border-slate-700/50 p-4 mb-4">
        <h6 className="text-lg font-semibold mb-2 text-gray-900 dark:text-white">Course Progress</h6>
        {courseProgress.length === 0 ? (
          <div className="rounded-lg border border-dashed border-slate-300 p-5 dark:border-slate-700">
            <p className="text-sm text-slate-500 dark:text-slate-400">
              No enrolled courses yet. Browse courses to start building your learning progress.
            </p>
            <button
              type="button"
              onClick={() => router.push('/courses')}
              className="mt-3 text-sm font-semibold text-indigo-600 hover:text-indigo-700 dark:text-indigo-400"
            >
              Browse courses
            </button>
          </div>
        ) : courseProgress.map(course => (
          <button
            key={course.id}
            type="button"
            onClick={() => router.push(`/courses/${course.id}`)}
            className="mb-3 block w-full rounded-lg p-2 text-left transition-colors hover:bg-slate-50 dark:hover:bg-slate-800/70"
          >
            <div className="flex justify-between mb-1">
              <p className="text-base text-gray-900 dark:text-slate-200">{course.name}</p>
              <p className="text-sm text-gray-500 dark:text-slate-400">{course.progressPercentage}%</p>
            </div>
            <div className="w-full h-2">
              <ProgressBar value={course.progressPercentage} className="h-2 rounded-full" />
            </div>
            <p className="text-xs text-gray-400 dark:text-slate-500 mt-1">
              Last synced: {formatLastUpdated(course.lastUpdated)}
            </p>
          </button>
        ))}
      </div>

      {/* Unit Progress */}
      <div className="bg-white/80 dark:bg-slate-800/50 backdrop-blur-sm rounded-lg shadow-sm border border-gray-100 dark:border-slate-700/50 p-4 mb-4">
        <h6 className="text-lg font-semibold mb-2 text-gray-900 dark:text-white">Unit Progress</h6>
        {unitProgress.length === 0 ? (
          <p className="rounded-lg border border-dashed border-slate-300 p-5 text-sm text-slate-500 dark:border-slate-700 dark:text-slate-400">
            Unit progress appears here after you begin lessons in an enrolled course.
          </p>
        ) : unitProgress.map(unit => (
          <button
            key={unit.id}
            type="button"
            disabled={!unit.courseId}
            onClick={() => unit.courseId && router.push(`/courses/${unit.courseId}/units/${unit.id}`)}
            className="mb-3 block w-full rounded-lg p-2 text-left transition-colors hover:bg-slate-50 disabled:cursor-default dark:hover:bg-slate-800/70"
          >
            <div className="flex justify-between mb-1">
              <p className="text-base text-gray-900 dark:text-slate-200">
                {unit.name} ({courseProgress.find(c => c.id === unit.courseId)?.name})
              </p>
              <p className="text-sm text-gray-500 dark:text-slate-400">{unit.progressPercentage}%</p>
            </div>
            <div className="w-full h-2">
              <ProgressBar value={unit.progressPercentage} className="h-2 rounded-full" />
            </div>
            <p className="text-xs text-gray-400 dark:text-slate-500 mt-1">
              Last synced: {formatLastUpdated(unit.lastUpdated)}
            </p>
          </button>
        ))}
      </div>

      {/* Peer Comparison */}
      <div className="bg-white/80 dark:bg-slate-800/50 backdrop-blur-sm rounded-lg shadow-sm border border-gray-100 dark:border-slate-700/50 p-4">
        <h6 className="text-lg font-semibold mb-2 text-gray-900 dark:text-white">Peer Comparison</h6>
        {peerStats && (
          <div>
            <p className="text-sm text-gray-500 dark:text-slate-400 mb-2">
              You're in the top {Math.round(peerStats.userPercentile)}%
            </p>
            <div className="mt-2">
              <p className="text-sm text-gray-600 dark:text-slate-300">
                Average Completion: {Math.round(peerStats.averageScore)}%
              </p>
              <p className="text-sm text-gray-600 dark:text-slate-300">
                Your Completion: {Math.round(peerStats.userScore)}%
              </p>
            </div>
          </div>
        )}
        {!peerStats && (
          <p className="text-sm text-gray-500 dark:text-slate-400">
            Peer comparisons will appear when enough cohort progress data is available.
          </p>
        )}
      </div>

      {/* Goals Integration */}
      <div className="mt-4">
        <GoalsProgressWidget />
      </div>
    </div>
  );
};
