// src/modules/learning/services/learning-goals.service.ts
import {
  Injectable,
  NotFoundException,
  BadRequestException,
  Logger,
} from '@nestjs/common';
import { PrismaService } from '../../../../infrastructure/prisma/prisma.service';
import {
  Prisma,
  ProgressStatus,
  LearningGoal,
  LearningGoalProgress,
  GoalCategory,
  GoalPriority,
  GoalStatus,
  GoalType,
  ProgressEntryType,
} from '@prisma/client';
import { EventEmitter2 } from '@nestjs/event-emitter';
import {
  GoalFiltersDto,
  CreateLearningGoalDto,
  MilestoneDto,
  RecommendedGoalDto,
  RecommendedGoalsResponseDto,
  GoalRecommendationSource,
  LearningGoalWithMilestones,
  Milestone,
} from '../../../../common/dto/learning-goals.dto';
import { PeerProgress } from '#common/dto/progress.dto';
import { getErrorMessage } from '#common/utils/error.utils';
import { LearningAnalyticsService } from '../../../ai-analytics/services/learning-analytics.service';
import { NotificationsService } from '#modules/engagement-communication/services/notifications.service';

@Injectable()
export class LearningGoalsService {
  private readonly logger = new Logger(LearningGoalsService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly eventEmitter: EventEmitter2,
    private readonly learningAnalyticsService: LearningAnalyticsService,
    private readonly notificationsService: NotificationsService,
  ) {}

  private mapPriorityToNumber(priority: GoalPriority): number {
    switch (priority) {
      case 'high':
        return 3;
      case 'medium':
        return 2;
      case 'low':
        return 1;
      default:
        return 0;
    }
  }

  async create(
    createDto: CreateLearningGoalDto,
    userId: string,
  ): Promise<LearningGoal> {
    const user = await this.prisma.user.findUnique({ where: { id: userId } });
    if (!user) {
      throw new NotFoundException('User not found');
    }

    // GOAL-005: Validate dependency if provided
    if (createDto.dependsOnGoalId) {
      const isValid = await this.validateNoCycle(
        'new_goal', // Temporary ID for validation
        createDto.dependsOnGoalId,
      );
      if (!isValid) {
        throw new BadRequestException(
          'Circular dependency detected in goal setting.',
        );
      }
    }

    await this.validateRelatedResources(createDto);

    if (createDto.targetDate) {
      const conflicts = await this.detectConflicts(
        userId,
        createDto.targetDate,
      );
      if (conflicts.length > 0) {
        this.logger.warn(
          `Goal conflict detected for user ${userId}. ${conflicts.length} overlapping goals found.`,
        );
        // Note: In a real frontend integration, this would return a warning flag in the response
      }
    }

    const milestones: Milestone[] =
      createDto.milestones?.map((milestone, index) => ({
        ...milestone,
        id: milestone.id || `milestone_${Date.now()}_${index}`,
        completed: milestone.completed ?? false,
      })) || [];

    try {
      // Strip empty strings for optional FK fields so Prisma doesn't reject them
      const orNull = (v?: string | null) => (v && v.trim() !== '' ? v : undefined);

      const goal = await (this.prisma as any).learningGoal.create({
        data: {
          title: createDto.title,
          description: createDto.description,
          category: createDto.category,
          priority: createDto.priority
            ? this.mapPriorityToNumber(createDto.priority)
            : 1,
          startDate: createDto.startDate,
          targetDate: createDto.targetDate,
          userId,
          ...(orNull(createDto.courseId) ? { courseId: orNull(createDto.courseId) } : {}),
          ...(orNull(createDto.topicId) ? { topicId: orNull(createDto.topicId) } : {}),
          ...(orNull(createDto.materialId) ? { materialId: orNull(createDto.materialId) } : {}),
          ...(orNull(createDto.learningPathId) ? { learningPathId: orNull(createDto.learningPathId) } : {}),
          ...(orNull(createDto.dependsOnGoalId) ? { dependsOnGoalId: orNull(createDto.dependsOnGoalId) } : {}),
          streakCount: 0,
          status: ProgressStatus.inProgress,
          progress: 0,
          metadata: {
            milestones,
            targetCriteria: createDto.targetCriteria,
            progressTracking: createDto.progressTracking || {},
            reminderSettings: createDto.reminderSettings || {},
          } as any,
        },
        include: {
          user: true,
          course: true,
          LearningGoalProgress: true,
          dependsOn: true,
        },
      });

      await this.addProgressEntry(goal.id, userId, {
        entryType: ProgressEntryType.automatic,
        progressValue: 0,
        notes: 'Goal created',
        metadata: { autoGenerated: true },
      });

      this.eventEmitter.emit('learning-goal.created', {
        goalId: goal.id,
        userId,
        data: goal,
      });

      await this.notificationsService.create(
        userId,
        `New goal set: ${createDto.title}`,
        'info',
        { goalId: goal.id, type: 'goal_created' },
      );

      return goal;
    } catch (error) {
      throw new BadRequestException(
        `Failed to create learning goal: ${getErrorMessage(error)}`,
      );
    }
  }

  /**
   * Detects if a new goal conflicts with existing goals (deadlines within 7 days).
   */
  async detectConflicts(
    userId: string,
    targetDate: Date,
  ): Promise<LearningGoal[]> {
    const startWindow = new Date(targetDate);
    startWindow.setDate(startWindow.getDate() - 7);
    const endWindow = new Date(targetDate);
    endWindow.setDate(endWindow.getDate() + 7);

    return await this.prisma.learningGoal.findMany({
      where: {
        userId,
        status: { not: ProgressStatus.completed },
        targetDate: {
          gte: startWindow,
          lte: endWindow,
        },
      },
    });
  }

  async findAll(
    userId: string,
    filters: Partial<GoalFiltersDto> = {},
  ): Promise<LearningGoal[]> {
    const where: Prisma.LearningGoalWhereInput = { userId };

    // Handle status filter - "upcoming" is a special filter that checks targetDate
    if (filters.upcoming) {
      const now = new Date();
      where.targetDate = { gte: now };
      where.status = { not: ProgressStatus.completed };
    } else if (filters.status) {
      if (filters.status === 'active') {
        where.status = ProgressStatus.inProgress;
      } else {
        where.status = filters.status;
      }
    }

    if (filters.category) {
      where.category = filters.category;
    }
    if (filters.priority) {
      where.priority = this.mapPriorityToNumber(filters.priority);
    }

    if (filters.dueSoon) {
      const nextWeek = new Date();
      nextWeek.setDate(nextWeek.getDate() + 7);
      where.targetDate = { lte: nextWeek };
      where.status = { not: ProgressStatus.completed };
    }

    if (filters.overdue) {
      where.targetDate = { lt: new Date() };
      where.status = { not: ProgressStatus.completed };
    }

    if (filters.search) {
      where.OR = [
        { title: { contains: filters.search, mode: 'insensitive' } },
        { description: { contains: filters.search, mode: 'insensitive' } },
      ];
    }

    this.logger.debug(`FindAll filters: ${JSON.stringify(filters)}`);
    this.logger.debug(`Prisma where: ${JSON.stringify(where)}`);

    this.logger.debug(`FindAll filters: ${JSON.stringify(filters)}`);
    this.logger.debug(`Prisma where: ${JSON.stringify(where)}`);

    try {
      // Temporarily simplify query to isolate the "(not available)" column error
      const goals = await this.prisma.learningGoal.findMany({
        where,
        // include: {
        //   course: true,
        //   user: true,
        //   LearningGoalProgress: {
        //     orderBy: { createdAt: 'desc' },
        //     take: 5,
        //   },
        // },
        // orderBy: [{ priority: 'desc' }, { targetDate: 'asc' }],
      });
      return goals;
    } catch (error) {
      this.logger.error(`Error in findAll: ${getErrorMessage(error)}`, (error as any)?.stack);
      throw new BadRequestException(
        `Failed to retrieve goals: ${getErrorMessage(error)}`,
      );
    }
  }

  getSmartSuggestions(
    goalData: Partial<CreateLearningGoalDto>,
  ): Record<string, string> {
    return {
      specific: `Make the goal more specific: ${goalData.title}`,
      measurable: `Define how to measure progress for: ${goalData.title}`,
      achievable: `Ensure the goal is achievable: ${goalData.title}`,
      relevant: `Align the goal with broader objectives: ${goalData.title}`,
      timeBound: `Set a deadline for the goal: ${goalData.title}`,
    };
  }

  async getAnalytics(userId: string): Promise<any> {
    try {
      const goals = await this.prisma.learningGoal.findMany({
        where: { userId },
        select: {
          id: true,
          title: true,
          status: true,
          category: true,
          priority: true,
          progress: true,
          targetDate: true,
          completedAt: true,
          createdAt: true,
          streakCount: true,
        },
      });

      const totalGoals = goals.length;
      const completedGoals = goals.filter(
        (g) => g.status === ProgressStatus.completed,
      ).length;
      const activeGoals = goals.filter(
        (g) => g.status === ProgressStatus.active,
      ).length;
      const overdue = goals.filter((g) => {
        if (g.status !== ProgressStatus.active) {
          return false;
        }
        if (!g.targetDate) {
          return false;
        }
        const td = g.targetDate as unknown as Date;
        return new Date(td) < new Date();
      }).length;

      // goals by priority
      const goalsByPriority = goals.reduce((acc: Record<string, number>, g) => {
        const p = String(g.priority ?? '0');
        acc[p] = (acc[p] || 0) + 1;
        return acc;
      }, {});

      // average completion time in days
      const completed = goals.filter(
        (g) =>
          g.status === ProgressStatus.completed && g.completedAt && g.createdAt,
      );
      const avgCompletionDays =
        completed.length > 0
          ? completed.reduce((sum, g) => {
              const created = g.createdAt as unknown as Date;
              const completedAt = g.completedAt as unknown as Date;
              return (
                sum +
                (completedAt.getTime() - created.getTime()) /
                  (1000 * 60 * 60 * 24)
              );
            }, 0) / completed.length
          : 0;

      // streaks
      const currentStreak = Math.max(
        0,
        ...goals.map((g) => g.streakCount || 0),
      );
      const longestStreak = currentStreak; // placeholder: we don't have historical data here
      const streakGoalIds = goals
        .filter((g) => (g.streakCount || 0) > 0)
        .map((g) => g.id);

      // upcoming deadlines
      const now = new Date();
      const upcomingDeadlines = goals
        .filter((g) => g.targetDate && new Date(g.targetDate) > now)
        .map((g) => ({
          goalId: g.id,
          title: g.title || '',
          targetDate: (g.targetDate as unknown as Date).toISOString(),
          daysRemaining: Math.ceil(
            ((g.targetDate as unknown as Date).getTime() - now.getTime()) /
              (1000 * 60 * 60 * 24),
          ),
        }));

      return {
        userId,
        totalGoals,
        completedGoals,
        activeGoals,
        overdueGoals: overdue,
        completionRate:
          totalGoals > 0 ? (completedGoals / totalGoals) * 100 : 0,
        goalsByCategory: this.groupGoalsByCategory(goals),
        goalsByPriority,
        averageCompletionTimeDays: Math.round(avgCompletionDays),
        streakData: {
          currentStreak,
          longestStreak,
        },
        streakGoalIds,
        upcomingDeadlines,
      };
    } catch (error) {
      this.logger.error('Error getting goal analytics:', error);
      throw new BadRequestException('Failed to get goal analytics');
    }
  }

  private groupGoalsByCategory(
    goals: Partial<LearningGoal>[],
  ): Record<string, number> {
    return goals.reduce((acc: Record<string, number>, goal) => {
      const category = goal.category || 'uncategorized';
      acc[category] = (acc[category] || 0) + 1;
      return acc;
    }, {});
  }

  async findOne(
    id: string,
    userId: string,
  ): Promise<LearningGoalWithMilestones> {
    try {
      const goal = await this.prisma.learningGoal.findFirst({
        where: { id, userId },
        include: {
          course: true,
          LearningGoalProgress: {
            orderBy: { createdAt: 'desc' },
          },
        },
      });

      if (!goal) {
        throw new NotFoundException('Learning goal not found');
      }

      const metadata = goal.metadata as Prisma.JsonObject;
      const milestones = (metadata?.milestones as unknown as Milestone[]) || [];

      return {
        ...goal,
        milestones,
      };
    } catch (error) {
      if (error instanceof NotFoundException) {
        throw error;
      }
      throw new BadRequestException(
        `Failed to retrieve goal: ${getErrorMessage(error)}`,
      );
    }
  }

  async update(
    id: string,
    updateDto: Partial<CreateLearningGoalDto>,
    userId: string,
  ): Promise<LearningGoal> {
    const goal = await this.findOne(id, userId);

    // GOAL-005: Validate circular dependencies
    if (updateDto.dependsOnGoalId !== undefined) {
      const isValid = await this.validateNoCycle(id, updateDto.dependsOnGoalId);
      if (!isValid) {
        throw new BadRequestException(
          'Circular dependency detected. A goal cannot depend on itself or create a dependency cycle.',
        );
      }
    }

    let completedAt: Date | undefined;
    let progress = updateDto.progressPercentage ?? goal.progress;

    if (updateDto.status && updateDto.status !== goal.status) {
      if (updateDto.status === GoalStatus.completed) {
        completedAt = new Date();
        progress = 100;

        await this.prisma.learningGoalProgress.create({
          data: {
            learningGoalId: id,
            userId,
            status: ProgressStatus.completed,
            progress: 100,
            completedAt: new Date(),
          },
        });

        this.eventEmitter.emit('learning-goal.completed', {
          goalId: id,
          userId,
          completionData: { completedAt },
        });

        await this.notificationsService.create(
          userId,
          `Congratulations! You completed the goal: ${goal.title}`,
          'success',
          { goalId: id, type: 'goal_completed' },
        );
      } else if (updateDto.status === GoalStatus.cancelled) {
        // GOAL-005: Block dependent goals
        await this.blockDependentGoals(
          id,
          userId,
          `Parent goal "${goal.title}" was cancelled`,
        );
      }
    }

    // GOAL-005: Cascade deadline changes
    if (updateDto.targetDate && goal.targetDate) {
      const oldDate = new Date(goal.targetDate);
      const newDate = new Date(updateDto.targetDate);

      if (oldDate.getTime() !== newDate.getTime()) {
        await this.cascadeDeadlineToDependent(id, newDate, userId);
      }
    }

    try {
      const updatedGoal = await (this.prisma as any).learningGoal.update({
        where: { id },
        data: {
          title: updateDto.title,
          description: updateDto.description,
          category: updateDto.category,
          priority: updateDto.priority
            ? this.mapPriorityToNumber(updateDto.priority)
            : undefined,
          startDate: updateDto.startDate,
          targetDate: updateDto.targetDate,
          progress,
          completedAt,
          status: updateDto.status as unknown as ProgressStatus,
          updatedAt: new Date(),
          dependsOnGoalId: updateDto.dependsOnGoalId, // GOAL-005
          topicId: updateDto.topicId,
          materialId: updateDto.materialId,
          learningPathId: updateDto.learningPathId,
          blockedReason: updateDto.blockedReason, // GOAL-005
          metadata: {
            ...((goal.metadata as Prisma.JsonObject) || {}),
            milestones: updateDto.milestones,
            targetCriteria: updateDto.targetCriteria,
            progressTracking: updateDto.progressTracking,
          },
        },
        include: {
          user: true,
          course: true,
          LearningGoalProgress: {
            orderBy: { updatedAt: 'desc' },
            take: 5,
          },
          dependsOn: true,
          dependencies: true,
        },
      });

      this.eventEmitter.emit('learning-goal.updated', {
        goalId: id,
        userId,
        data: updatedGoal,
        changes: updateDto,
      });

      return updatedGoal;
    } catch (error) {
      throw new BadRequestException(
        `Failed to update goal: ${getErrorMessage(error)}`,
      );
    }
  }

  async updateMilestone(
    goalId: string,
    milestoneId: string,
    userId: string,
    updateData: { completed?: boolean; completedAt?: Date; notes?: string },
  ): Promise<LearningGoal> {
    const goal = await this.findOne(goalId, userId);

    const milestones = goal.milestones;
    if (!milestones.length) {
      throw new NotFoundException('Goal has no milestones');
    }

    const milestoneIndex = milestones.findIndex((m) => m.id === milestoneId);
    if (milestoneIndex === -1) {
      throw new NotFoundException('Milestone not found');
    }

    const milestone = milestones[milestoneIndex];
    const originalCompleted = milestone.completed;

    milestones[milestoneIndex] = {
      ...milestone,
      ...updateData,
      completedAt: updateData.completed
        ? updateData.completedAt || new Date()
        : milestone.completedAt,
    };

    try {
      const updatedGoal = await this.prisma.learningGoal.update({
        where: { id: goalId },
        data: {
          metadata: {
            ...((goal.metadata as Prisma.JsonObject) || {}),
            milestones,
          },
          updatedAt: new Date(),
        },
        include: {
          course: true,
          LearningGoalProgress: {
            orderBy: { createdAt: 'desc' },
          },
        },
      });

      if (updateData.completed && !originalCompleted) {
        await this.addProgressEntry(goalId, userId, {
          entryType: ProgressEntryType.milestone,
          progressValue: milestone.targetValue,
          notes: updateData.notes || `Milestone completed: ${milestone.title}`,
          metadata: { milestoneId, milestoneTitle: milestone.title },
        });

        this.eventEmitter.emit('learning-goal.milestone.achieved', {
          goalId,
          milestoneId,
          userId,
          milestone: milestones[milestoneIndex],
        });

        await this.notificationsService.create(
          userId,
          `Milestone achieved: ${milestones[milestoneIndex].title}`,
          'success',
          { goalId, milestoneId, type: 'milestone_completed' },
        );
      }

      return updatedGoal;
    } catch (error) {
      throw new BadRequestException(
        `Failed to update milestone: ${getErrorMessage(error)}`,
      );
    }
  }

  async remove(id: string, userId: string): Promise<void> {
    const goal = await this.findOne(id, userId);

    try {
      await this.prisma.learningGoal.delete({
        where: { id },
      });

      this.eventEmitter.emit('learning-goal.deleted', {
        goalId: id,
        userId,
        data: goal,
      });
    } catch (error) {
      throw new BadRequestException(
        `Failed to delete goal: ${getErrorMessage(error)}`,
      );
    }
  }

  async addProgressEntry(
    goalId: string,
    userId: string,
    progressData: {
      entryType: ProgressEntryType;
      progressValue: number;
      notes?: string;
      metadata?: Prisma.JsonValue;
      context?: Prisma.JsonValue;
      celebrationData?: Prisma.JsonValue;
    },
  ): Promise<LearningGoalProgress> {
    const goal = await this.findOne(goalId, userId);
    const metadata = goal.metadata as Prisma.JsonObject;
    const targetCriteria = metadata?.targetCriteria as any;

    const targetValue = targetCriteria?.targetValue || 100;
    const progressPercentage =
      targetValue > 0
        ? Math.min((progressData.progressValue / targetValue) * 100, 100)
        : 0;

    try {
      const progressEntry = await this.prisma.learningGoalProgress.create({
        data: {
          learningGoalId: goalId,
          userId,
          progress: progressPercentage,
          status:
            progressPercentage >= 100
              ? ProgressStatus.completed
              : ProgressStatus.inProgress,
          completedAt: progressPercentage >= 100 ? new Date() : null,
        },
      });

      const isCompleted = progressPercentage >= 100;
      await this.prisma.learningGoal.update({
        where: { id: goalId },
        data: {
          progress: progressPercentage,
          status: isCompleted ? ProgressStatus.completed : undefined,
          completedAt: isCompleted ? new Date() : undefined,
          updatedAt: new Date(),
        },
      });

      if (isCompleted) {
        this.eventEmitter.emit('learning-goal.completed', {
          goalId,
          userId,
          completionData: { completedAt: new Date() },
        });

        await this.notificationsService.create(
          userId,
          `Congratulations! You completed the goal: ${goal.title}`,
          'success',
          { goalId, type: 'goal_completed' },
        );
      }

      this.checkMilestoneAchievements(goal, progressData.progressValue);

      void this.updateStreak(goal);

      this.eventEmitter.emit('learning-goal.progress.added', {
        goalId,
        userId,
        progressEntry,
        newProgress: progressPercentage,
      });

      return progressEntry;
    } catch (error) {
      throw new BadRequestException(
        `Failed to add progress entry: ${getErrorMessage(error)}`,
      );
    }
  }

  async getGoalProgress(
    goalId: string,
    userId: string,
    limit?: number,
  ): Promise<LearningGoalProgress[]> {
    await this.findOne(goalId, userId);

    try {
      return await this.prisma.learningGoalProgress.findMany({
        where: { learningGoalId: goalId },
        orderBy: { createdAt: 'desc' },
        take: limit,
      });
    } catch (error) {
      throw new BadRequestException(
        `Failed to retrieve goal progress: ${getErrorMessage(error)}`,
      );
    }
  }

  async getPeerProgress(studyGroupId: string): Promise<PeerProgress[]> {
    try {
      const members = await this.prisma.studyGroupMember.findMany({
        where: {
          studyGroupId,
          status: 'active',
        },
        include: {
          user: {
            select: {
              id: true,
              email: true,
            },
          },
        },
      });

      if (!members.length) {
        return [];
      }

      const userIds = members.map((member) => member.userId);

      const courseProgresses = await this.prisma.progress.findMany({
        where: {
          userId: { in: userIds },
          courseId: { not: null },
          materialId: null,
          topicId: null,
        },
        orderBy: {
          lastAccessedAt: 'desc',
        },
      });

      const progressMap = new Map<
        string,
        { percent: number; lastActive: Date | null }
      >();
      for (const progress of courseProgresses as any[]) {
        if (!progressMap.has(progress.userId)) {
          progressMap.set(progress.userId, {
            percent: progress.progressPercentage,
            lastActive: progress.lastAccessedAt,
          });
        }
      }

      return members.map(
        (member): PeerProgress => ({
          userId: member.user.id,
          name: member.user.email,
          avatar: null,
          progress: progressMap.get(member.userId) ?? {
            percent: 0,
            lastActive: null,
          },
        }),
      );
    } catch (error) {
      throw new BadRequestException(
        `Failed to get peer progress: ${getErrorMessage(error)}`,
      );
    }
  }

  async getTopPerformers(limit = 5): Promise<PeerProgress[]> {
    try {
      const topUsers = await this.prisma.progress.findMany({
        where: {
          courseId: { not: null },
          materialId: null,
          topicId: null,
          progressPercentage: {
            gt: 0,
          },
        },
        orderBy: {
          progressPercentage: 'desc',
        },
        take: limit,
        include: {
          user: {
            select: {
              id: true,
              email: true,
            },
          },
        },
      });

      return topUsers.map(
        (progress: any): PeerProgress => ({
          userId: progress.user.id,
          name: progress.user.email,
          avatar: null,
          progress: {
            percent: progress.progressPercentage,
            lastActive: progress.lastAccessedAt,
          },
        }),
      );
    } catch (error) {
      throw new BadRequestException(
        `Failed to get top performers: ${getErrorMessage(error)}`,
      );
    }
  }

  generateSmartSuggestions(
    goalData: Partial<CreateLearningGoalDto>,
  ): Record<string, string> {
    return {
      specific: this.generateSpecificSuggestion(goalData),
      measurable: this.generateMeasurableSuggestion(goalData),
      achievable: this.generateAchievableSuggestion(goalData),
      relevant: this.generateRelevantSuggestion(goalData),
      timeBound: this.generateTimeBoundSuggestion(goalData),
    };
  }

  private async validateRelatedResources(
    createDto: CreateLearningGoalDto,
  ): Promise<void> {
    if (createDto.courseId) {
      const course = await this.prisma.course.findUnique({
        where: { id: createDto.courseId },
      });
      if (!course) {
        throw new NotFoundException('Course not found');
      }
    }
  }

  private checkMilestoneAchievements(
    goal: LearningGoalWithMilestones,
    currentValue: number,
  ): void {
    const milestones = goal.milestones || [];
    if (!milestones.length) {
      return;
    }

    let milestonesChanged = false;

    for (const milestone of milestones) {
      if (!milestone.completed && currentValue >= milestone.targetValue) {
        milestone.completed = true;
        milestone.completedAt = new Date();
        milestonesChanged = true;

        this.eventEmitter.emit('learning-goal.milestone.achieved', {
          goalId: goal.id,
          milestoneId: milestone.id,
          userId: goal.userId,
          milestone,
        });

        void this.notificationsService.create(
          goal.userId,
          `Milestone achieved: ${milestone.title}`,
          'success',
          {
            goalId: goal.id,
            milestoneId: milestone.id,
            type: 'milestone_completed',
          },
        );
      }
    }

    if (milestonesChanged) {
      void this.prisma.learningGoal.update({
        where: { id: goal.id },
        data: {
          metadata: {
            ...((goal.metadata as Prisma.JsonObject) || {}),
            milestones,
          },
        },
      });
    }
  }

  private async updateStreak(goal: LearningGoal): Promise<void> {
    const today = new Date();
    const lastUpdate = goal.updatedAt;
    let streakCount = goal.streakCount || 0;

    if (!lastUpdate) {
      streakCount = 1;
    } else {
      const daysDiff = Math.floor(
        (today.getTime() - lastUpdate.getTime()) / (1000 * 60 * 60 * 24),
      );
      if (daysDiff === 1) {
        streakCount += 1;
      } else if (daysDiff > 1) {
        streakCount = 1;
      }
    }

    await this.prisma.learningGoal.update({
      where: { id: goal.id },
      data: { streakCount },
    });
  }

  private calculateCompletionPoints(goal: LearningGoalWithMilestones): number {
    let points = 100;

    switch (goal.priority) {
      case 3: // critical - was GoalPriority.critical
        points += 50;
        break;
      case 2: // high - was GoalPriority.high
        points += 30;
        break;
      case 1: // medium - was GoalPriority.medium
        points += 10;
        break;
      case 0: // low - was GoalPriority.low
        points += 5;
        break;
    }

    points += (goal.streakCount || 0) * 5;

    const milestoneCount = goal.milestones?.length || 0;
    points += milestoneCount * 10;

    return points;
  }

  private generateSpecificSuggestion(
    goalData: Partial<CreateLearningGoalDto>,
  ): string {
    const category = goalData.category;
    const cat = category as GoalCategory;
    const suggestions: { [key in GoalCategory]?: string } = {
      [GoalCategory.study_time]:
        'Study for a specific number of hours per day/week',
      [GoalCategory.course_completion]: 'Complete specific courses or modules',
      [GoalCategory.assessment_score]:
        'Achieve a specific score on assessments',
      [GoalCategory.skill_mastery]:
        'Master specific clinical skills or competencies',
      [GoalCategory.streak_maintenance]:
        'Maintain consistent daily study habits',
      [GoalCategory.learning_path]: 'Complete milestones in a learning path',
      [GoalCategory.clinical_cases]: 'Complete clinical case studies',
    };

    return suggestions[cat] || 'Define exactly what you want to achieve';
  }

  private generateMeasurableSuggestion(
    goalData: Partial<CreateLearningGoalDto>,
  ): string {
    const targetCriteria = goalData.targetCriteria;
    if (targetCriteria?.type === 'numeric') {
      return `Track progress towards ${targetCriteria.targetValue} ${
        targetCriteria.unit || 'units'
      }`;
    }
    return 'Define how you will measure progress with specific numbers or percentages';
  }

  private generateAchievableSuggestion(
    _goalData: Partial<CreateLearningGoalDto>,
  ): string {
    return 'Ensure the goal is challenging but realistic based on your current schedule and commitments';
  }

  private generateRelevantSuggestion(
    goalData: Partial<CreateLearningGoalDto>,
  ): string {
    const category = goalData.category;
    const cat = category as GoalCategory;
    const suggestions: { [key in GoalCategory]?: string } = {
      [GoalCategory.assessment_score]:
        'Aligns with assessment preparation timeline',
      [GoalCategory.skill_mastery]: 'Supports clinical competency development',
      [GoalCategory.custom]: 'Relevant to your chosen medical specialty',
      [GoalCategory.learning_path]: 'Supports structured learning journey',
      [GoalCategory.clinical_cases]: 'Enhances clinical case analysis skills',
    };

    return (
      suggestions[cat] ||
      'Ensure this goal supports your broader medical education objectives'
    );
  }

  private generateTimeBoundSuggestion(
    goalData: Partial<CreateLearningGoalDto>,
  ): string {
    const startDate = goalData.startDate;
    const targetDate = goalData.targetDate;

    if (startDate && targetDate) {
      const days = Math.ceil(
        (targetDate.getTime() - startDate.getTime()) / (1000 * 60 * 60 * 24),
      );
      return `Complete within ${days} days (${Math.ceil(days / 7)} weeks)`;
    }

    return 'Set a specific deadline for achieving this goal';
  }

  async getRecommendedGoals(
    userId: string,
    limit: number = 5,
  ): Promise<RecommendedGoalsResponseDto> {
    this.logger.log(`Fetching recommendations for user ${userId}`);

    try {
      // 1. Get study recommendations from learning-analytics service (gRPC-based)
      const studyRecs =
        await this.learningAnalyticsService.generateStudyRecommendations(
          userId,
          [],
        );

      // 2. Get collaborative recommendations from peers
      const peerRecs =
        await this.learningAnalyticsService.getCollaborativeRecommendations(
          userId,
          5,
        );

      // 3. Get trending learning paths
      const trendingPaths =
        await this.learningAnalyticsService.getTrendingPaths(5);

      // 4. Fetch Exam Mappings for all relevant topics to boost priority
      const examMappings = await this.prisma.examMapping.findMany({
        where: {
          topicId: {
            in: studyRecs
              .map((r) => r.id)
              .concat(peerRecs.map((p) => p.item_id)),
          },
        },
        include: { topic: true },
      });

      const mappingMap = new Map(examMappings.map((m) => [m.topicId, m]));

      const recommendations: RecommendedGoalDto[] = [];

      // Add study recommendations with weight boost
      studyRecs.forEach((rec) => {
        const mapping = mappingMap.get(rec.id);
        const stakeInfo = mapping
          ? ` - 🔥 High Stakes: ${mapping.examType}`
          : '';

        recommendations.push({
          title: `Study: ${rec.title || 'Recommended Material'}`,
          description: `Complete study materials: ${rec.title || 'Recommended learning material'}`,
          category: GoalCategory.course_completion,
          type: GoalType.shortTerm,
          recommendationReason: `Priority: ${rec.priority || 'Medium'} - Type: ${rec.type}${stakeInfo}`,
          recommendationSource: GoalRecommendationSource.PERFORMANCE_ANALYTICS,
          relatedId: rec.id,
          examStake: mapping?.correlation,
          examType: mapping?.examType,
        });
      });

      // Add collaborative recommendations
      peerRecs.forEach((rec) => {
        const mapping = mappingMap.get(rec.item_id);
        const stakeInfo = mapping
          ? ` - 🔥 High Stakes: ${mapping.examType}`
          : '';

        recommendations.push({
          title: `Peer Recommendation: ${rec.item_id}`,
          description: `Join peers learning similar content based on your profile`,
          category: GoalCategory.learning_path,
          type: GoalType.longTerm,
          recommendationReason: `Collaborative score: ${(rec.score * 100).toFixed(0)}% match${stakeInfo}`,
          recommendationSource: GoalRecommendationSource.PEER_TRENDS,
          relatedId: rec.item_id,
          examStake: mapping?.correlation,
          examType: mapping?.examType,
        });
      });

      // Add trending paths (ignoring mappings for paths for now)
      trendingPaths.forEach((path) => {
        recommendations.push({
          title: `Trending: Popular Learning Path`,
          description: `Master trending learning path: ${path.path_id}`,
          category: GoalCategory.learning_path,
          type: GoalType.longTerm,
          recommendationReason: `${path.enrollments} users are currently learning this path`,
          recommendationSource: GoalRecommendationSource.PERFORMANCE_ANALYTICS,
          relatedId: path.path_id,
        });
      });

      // Order by exam stake (highest first)
      recommendations.sort((a, b) => (b.examStake || 0) - (a.examStake || 0));

      // Fallback
      if (recommendations.length === 0) {
        recommendations.push({
          title: 'Maintain a 5-day Study Streak',
          description:
            'Log in and complete at least one learning activity every day for 5 days.',
          category: GoalCategory.streak_maintenance,
          type: GoalType.shortTerm,
          recommendationReason: 'Consistent study habits improve outcomes.',
          recommendationSource: GoalRecommendationSource.PERFORMANCE_ANALYTICS,
        });
      }

      return { recommendations: recommendations.slice(0, limit) };
    } catch (error) {
      this.logger.warn(
        `Error fetching gRPC recommendations for user ${userId}, returning defaults:`,
        error,
      );

      // Graceful fallback with default recommendations
      const defaultRecommendations: RecommendedGoalDto[] = [
        {
          title: 'Master Cardiovascular System',
          description:
            'Complete all modules and assessments related to the cardiovascular system.',
          category: GoalCategory.course_completion,
          type: GoalType.longTerm,
          recommendationReason: 'Popular area of focus among learners',
          recommendationSource: GoalRecommendationSource.PEER_TRENDS,
        },
        {
          title: 'Maintain Consistent Study Streak',
          description:
            'Log in and complete at least one learning activity every day.',
          category: GoalCategory.streak_maintenance,
          type: GoalType.shortTerm,
          recommendationReason:
            'Consistency is key to long-term retention and mastery',
          recommendationSource: GoalRecommendationSource.PERFORMANCE_ANALYTICS,
        },
      ];

      return { recommendations: defaultRecommendations.slice(0, limit) };
    }
  }

  /**
   * GOAL-005: Cascade deadline extension to dependent goals
   */
  async cascadeDeadlineToDependent(
    goalId: string,
    newDeadline: Date,
    userId: string,
  ): Promise<void> {
    const dependentGoals = await (this.prisma as any).learningGoal.findMany({
      where: {
        userId,
        dependsOnGoalId: goalId,
      },
    });

    if (dependentGoals.length === 0) {
      return;
    }

    // Calculate days extended
    const parentGoal = await this.prisma.learningGoal.findUnique({
      where: { id: goalId },
    });

    if (!parentGoal?.targetDate) {
      return;
    }

    const daysExtended = Math.ceil(
      (newDeadline.getTime() - new Date(parentGoal.targetDate).getTime()) /
        (1000 * 60 * 60 * 24),
    );

    // Cascade to all dependents
    for (const dep of dependentGoals) {
      if (dep.targetDate) {
        const newDepDeadline = new Date(dep.targetDate);
        newDepDeadline.setDate(newDepDeadline.getDate() + daysExtended);

        await this.prisma.learningGoal.update({
          where: { id: dep.id },
          data: {
            targetDate: newDepDeadline,
            metadata: {
              ...((dep.metadata as Prisma.JsonObject) || {}),
              extensionReason: `Parent goal ${parentGoal.title} extended by ${daysExtended} days`,
            },
          },
        });

        this.logger.log(
          `Cascaded ${daysExtended} day extension from goal ${goalId} to dependent ${dep.id}`,
        );

        // Recursively cascade to children's children
        await this.cascadeDeadlineToDependent(dep.id, newDepDeadline, userId);
      }
    }
  }

  /**
   * GOAL-005: Mark dependent goals as blocked when parent fails
   */
  async blockDependentGoals(
    parentGoalId: string,
    userId: string,
    reason: string,
  ): Promise<void> {
    const dependentGoals = await (this.prisma as any).learningGoal.findMany({
      where: {
        userId,
        dependsOnGoalId: parentGoalId,
      },
    });

    for (const dep of dependentGoals) {
      await (this.prisma as any).learningGoal.update({
        where: { id: dep.id },
        data: {
          blockedReason: reason,
          status: ProgressStatus.dropped,
        },
      });

      await this.notificationsService.create(
        userId,
        `Goal "${dep.title}" is now blocked: ${reason}`,
        'warning',
        { goalId: dep.id, parentGoalId, type: 'goal_blocked' },
      );

      this.logger.warn(
        `Goal ${dep.id} blocked due to parent goal ${parentGoalId} failure`,
      );
    }
  }

  /**
   * GOAL-005: Validate no circular dependencies
   */
  async validateNoCycle(
    goalId: string,
    potentialParentId: string | null,
  ): Promise<boolean> {
    if (!potentialParentId) {
      return true; // No dependency, no cycle
    }

    if (goalId === potentialParentId) {
      return false; // Direct self-reference
    }

    // Traverse up the dependency chain
    let currentId: string | null = potentialParentId;
    const visited = new Set<string>([goalId]);

    while (currentId) {
      if (visited.has(currentId)) {
        return false; // Cycle detected
      }

      visited.add(currentId);

      const parentGoalResult: any = await (
        this.prisma as any
      ).learningGoal.findUnique({
        where: { id: currentId },
        select: { dependsOnGoalId: true },
      });

      currentId = parentGoalResult?.dependsOnGoalId ?? null;
    }

    return true; // No cycle
  }

  async getActiveGoals(userId: string): Promise<LearningGoal[]> {
    return this.findAll(userId, { status: 'active' as any });
  }

  async getCompletedGoals(userId: string): Promise<LearningGoal[]> {
    return this.findAll(userId, { status: 'completed' as any });
  }

  async getUserStreakInfo(userId: string) {
    const analytics = await this.getAnalytics(userId);
    return analytics.streakData;
  }

  async startGoal(id: string, userId: string): Promise<LearningGoal> {
    return this.update(id, { status: 'active' as any }, userId);
  }

  async pauseGoal(id: string, userId: string): Promise<LearningGoal> {
    // Map paused to skipped status in the DB enum
    return this.update(id, { status: 'skipped' as any }, userId);
  }

  async completeGoal(id: string, userId: string): Promise<LearningGoal> {
    return this.update(id, { status: 'completed' as any }, userId);
  }

  async abandonGoal(id: string, userId: string): Promise<LearningGoal> {
    // Map cancelled to dropped status in the DB enum
    return this.update(id, { status: 'dropped' as any }, userId);
  }

  async updateGoalProgress(
    goalId: string,
    updateDto: any,
    userId: string,
  ): Promise<LearningGoalProgress> {
    return this.addProgressEntry(goalId, userId, {
      entryType: updateDto.entryType || ProgressEntryType.manual,
      progressValue: Number(updateDto.progressValue || updateDto.progress_value || 0),
      notes: updateDto.notes,
    });
  }

  async getGoalAnalytics(goalId: string): Promise<any> {
    const goal = await this.prisma.learningGoal.findUnique({
      where: { id: goalId },
      include: { LearningGoalProgress: true },
    });
    if (!goal) {
      throw new NotFoundException('Goal not found');
    }
    return {
      goalId,
      progress: goal.progress,
      status: goal.status,
      history: goal.LearningGoalProgress,
    };
  }

  async getGoalsOverview(userId: string): Promise<any> {
    try {
      return await this.learningAnalyticsService.getGoalAnalytics(userId);
    } catch (error) {
      this.logger.warn(
        `AI Analytics Service failed, falling back to local calculation: ${getErrorMessage(
          error,
        )}`,
      );
      return await this.getAnalytics(userId);
    }
  }
}
