# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import analytics_pb2 as analytics__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in analytics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalyticsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHealth = channel.unary_unary(
                '/analytics.AnalyticsService/GetHealth',
                request_serializer=analytics__pb2.HealthRequest.SerializeToString,
                response_deserializer=analytics__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.PredictPerformance = channel.unary_unary(
                '/analytics.AnalyticsService/PredictPerformance',
                request_serializer=analytics__pb2.PredictPerformanceRequest.SerializeToString,
                response_deserializer=analytics__pb2.PredictPerformanceResponse.FromString,
                _registered_method=True)
        self.GetEngagementMetrics = channel.unary_unary(
                '/analytics.AnalyticsService/GetEngagementMetrics',
                request_serializer=analytics__pb2.GetEngagementMetricsRequest.SerializeToString,
                response_deserializer=analytics__pb2.GetEngagementMetricsResponse.FromString,
                _registered_method=True)
        self.GetRecommendations = channel.unary_unary(
                '/analytics.AnalyticsService/GetRecommendations',
                request_serializer=analytics__pb2.GetRecommendationsRequest.SerializeToString,
                response_deserializer=analytics__pb2.GetRecommendationsResponse.FromString,
                _registered_method=True)
        self.UpdateAttemptMetrics = channel.unary_unary(
                '/analytics.AnalyticsService/UpdateAttemptMetrics',
                request_serializer=analytics__pb2.AttemptMetricsRequest.SerializeToString,
                response_deserializer=analytics__pb2.UpdateAttemptMetricsResponse.FromString,
                _registered_method=True)
        self.GetUserAbility = channel.unary_unary(
                '/analytics.AnalyticsService/GetUserAbility',
                request_serializer=analytics__pb2.GetUserAbilityRequest.SerializeToString,
                response_deserializer=analytics__pb2.GetUserAbilityResponse.FromString,
                _registered_method=True)
        self.GetNextAdaptiveQuestion = channel.unary_unary(
                '/analytics.AnalyticsService/GetNextAdaptiveQuestion',
                request_serializer=analytics__pb2.GetNextAdaptiveQuestionRequest.SerializeToString,
                response_deserializer=analytics__pb2.GetNextAdaptiveQuestionResponse.FromString,
                _registered_method=True)
        self.UpdateBkt = channel.unary_unary(
                '/analytics.AnalyticsService/UpdateBkt',
                request_serializer=analytics__pb2.UpdateBktRequest.SerializeToString,
                response_deserializer=analytics__pb2.UpdateBktResponse.FromString,
                _registered_method=True)
        self.GetUserLearningSummary = channel.unary_unary(
                '/analytics.AnalyticsService/GetUserLearningSummary',
                request_serializer=analytics__pb2.GetUserLearningSummaryRequest.SerializeToString,
                response_deserializer=analytics__pb2.UserLearningSummaryResponse.FromString,
                _registered_method=True)
        self.GetGoalAnalytics = channel.unary_unary(
                '/analytics.AnalyticsService/GetGoalAnalytics',
                request_serializer=analytics__pb2.GetGoalAnalyticsRequest.SerializeToString,
                response_deserializer=analytics__pb2.LearningGoalAnalyticsResponse.FromString,
                _registered_method=True)
        self.GetCourseStatistics = channel.unary_unary(
                '/analytics.AnalyticsService/GetCourseStatistics',
                request_serializer=analytics__pb2.GetCourseStatisticsRequest.SerializeToString,
                response_deserializer=analytics__pb2.CourseStatsResultResponse.FromString,
                _registered_method=True)
        self.GetLearningPathStatistics = channel.unary_unary(
                '/analytics.AnalyticsService/GetLearningPathStatistics',
                request_serializer=analytics__pb2.GetLearningPathStatisticsRequest.SerializeToString,
                response_deserializer=analytics__pb2.LearningPathStatsResultResponse.FromString,
                _registered_method=True)
        self.GetDetailedLearningAnalytics = channel.unary_unary(
                '/analytics.AnalyticsService/GetDetailedLearningAnalytics',
                request_serializer=analytics__pb2.GetDetailedLearningAnalyticsRequest.SerializeToString,
                response_deserializer=analytics__pb2.GetDetailedLearningAnalyticsResponse.FromString,
                _registered_method=True)
        self.CalculateCourseProgress = channel.unary_unary(
                '/analytics.AnalyticsService/CalculateCourseProgress',
                request_serializer=analytics__pb2.CalculateCourseProgressRequest.SerializeToString,
                response_deserializer=analytics__pb2.CourseProgress.FromString,
                _registered_method=True)
        self.GetUserDataForProfile = channel.unary_unary(
                '/analytics.AnalyticsService/GetUserDataForProfile',
                request_serializer=analytics__pb2.GetUserDataForProfileRequest.SerializeToString,
                response_deserializer=analytics__pb2.GetUserDataForProfileResponse.FromString,
                _registered_method=True)
        self.GetFilteredRecommendations = channel.unary_unary(
                '/analytics.AnalyticsService/GetFilteredRecommendations',
                request_serializer=analytics__pb2.GetFilteredRecommendationsRequest.SerializeToString,
                response_deserializer=analytics__pb2.GetFilteredRecommendationsResponse.FromString,
                _registered_method=True)
        self.GetUserFeatureVector = channel.unary_unary(
                '/analytics.AnalyticsService/GetUserFeatureVector',
                request_serializer=analytics__pb2.GetUserFeatureVectorRequest.SerializeToString,
                response_deserializer=analytics__pb2.GetUserFeatureVectorResponse.FromString,
                _registered_method=True)
        self.UpdateBktSkillMetrics = channel.unary_unary(
                '/analytics.AnalyticsService/UpdateBktSkillMetrics',
                request_serializer=analytics__pb2.UpdateBktSkillMetricsRequest.SerializeToString,
                response_deserializer=analytics__pb2.UpdateBktSkillMetricsResponse.FromString,
                _registered_method=True)
        self.BatchTrackEvents = channel.unary_unary(
                '/analytics.AnalyticsService/BatchTrackEvents',
                request_serializer=analytics__pb2.BatchEventRequest.SerializeToString,
                response_deserializer=analytics__pb2.BatchEventResponse.FromString,
                _registered_method=True)
        self.GetCollaborativeRecommendations = channel.unary_unary(
                '/analytics.AnalyticsService/GetCollaborativeRecommendations',
                request_serializer=analytics__pb2.CollaborativeRecommendationRequest.SerializeToString,
                response_deserializer=analytics__pb2.CollaborativeRecommendationResponse.FromString,
                _registered_method=True)
        self.GetTrendingPaths = channel.unary_unary(
                '/analytics.AnalyticsService/GetTrendingPaths',
                request_serializer=analytics__pb2.TrendingPathsRequest.SerializeToString,
                response_deserializer=analytics__pb2.TrendingPathsResponse.FromString,
                _registered_method=True)
        self.GetPathAnalytics = channel.unary_unary(
                '/analytics.AnalyticsService/GetPathAnalytics',
                request_serializer=analytics__pb2.PathAnalyticsRequest.SerializeToString,
                response_deserializer=analytics__pb2.PathAnalyticsResponse.FromString,
                _registered_method=True)
        self.GetCohortAnalytics = channel.unary_unary(
                '/analytics.AnalyticsService/GetCohortAnalytics',
                request_serializer=analytics__pb2.GetCohortAnalyticsRequest.SerializeToString,
                response_deserializer=analytics__pb2.CohortAnalyticsResponse.FromString,
                _registered_method=True)
        self.GetQuizAttemptHistory = channel.unary_unary(
                '/analytics.AnalyticsService/GetQuizAttemptHistory',
                request_serializer=analytics__pb2.QuizAttemptHistoryRequest.SerializeToString,
                response_deserializer=analytics__pb2.QuizAttemptHistoryResponse.FromString,
                _registered_method=True)
        self.GetRelatedResources = channel.unary_unary(
                '/analytics.AnalyticsService/GetRelatedResources',
                request_serializer=analytics__pb2.RelatedResourcesRequest.SerializeToString,
                response_deserializer=analytics__pb2.RelatedResourcesResponse.FromString,
                _registered_method=True)
        self.GenerateStudyRecommendations = channel.unary_unary(
                '/analytics.AnalyticsService/GenerateStudyRecommendations',
                request_serializer=analytics__pb2.StudyRecommendationsRequest.SerializeToString,
                response_deserializer=analytics__pb2.StudyRecommendationsResponse.FromString,
                _registered_method=True)
        self.GenerateNextSteps = channel.unary_unary(
                '/analytics.AnalyticsService/GenerateNextSteps',
                request_serializer=analytics__pb2.NextStepsRequest.SerializeToString,
                response_deserializer=analytics__pb2.NextStepsResponse.FromString,
                _registered_method=True)
        self.PredictBKT = channel.unary_unary(
                '/analytics.AnalyticsService/PredictBKT',
                request_serializer=analytics__pb2.PredictBKTRequest.SerializeToString,
                response_deserializer=analytics__pb2.PredictBKTResponse.FromString,
                _registered_method=True)
        self.PredictBurnModel = channel.unary_unary(
                '/analytics.AnalyticsService/PredictBurnModel',
                request_serializer=analytics__pb2.PredictBurnRequest.SerializeToString,
                response_deserializer=analytics__pb2.PredictBurnResponse.FromString,
                _registered_method=True)
        self.GetFocusRecommendations = channel.unary_unary(
                '/analytics.AnalyticsService/GetFocusRecommendations',
                request_serializer=analytics__pb2.GetFocusRecommendationsRequest.SerializeToString,
                response_deserializer=analytics__pb2.GetFocusRecommendationsResponse.FromString,
                _registered_method=True)


class AnalyticsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictPerformance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEngagementMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRecommendations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAttemptMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserAbility(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNextAdaptiveQuestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBkt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserLearningSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGoalAnalytics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCourseStatistics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLearningPathStatistics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDetailedLearningAnalytics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateCourseProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserDataForProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFilteredRecommendations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserFeatureVector(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBktSkillMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchTrackEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCollaborativeRecommendations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTrendingPaths(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPathAnalytics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCohortAnalytics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQuizAttemptHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRelatedResources(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateStudyRecommendations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateNextSteps(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictBKT(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictBurnModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFocusRecommendations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHealth,
                    request_deserializer=analytics__pb2.HealthRequest.FromString,
                    response_serializer=analytics__pb2.HealthResponse.SerializeToString,
            ),
            'PredictPerformance': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictPerformance,
                    request_deserializer=analytics__pb2.PredictPerformanceRequest.FromString,
                    response_serializer=analytics__pb2.PredictPerformanceResponse.SerializeToString,
            ),
            'GetEngagementMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEngagementMetrics,
                    request_deserializer=analytics__pb2.GetEngagementMetricsRequest.FromString,
                    response_serializer=analytics__pb2.GetEngagementMetricsResponse.SerializeToString,
            ),
            'GetRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecommendations,
                    request_deserializer=analytics__pb2.GetRecommendationsRequest.FromString,
                    response_serializer=analytics__pb2.GetRecommendationsResponse.SerializeToString,
            ),
            'UpdateAttemptMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAttemptMetrics,
                    request_deserializer=analytics__pb2.AttemptMetricsRequest.FromString,
                    response_serializer=analytics__pb2.UpdateAttemptMetricsResponse.SerializeToString,
            ),
            'GetUserAbility': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserAbility,
                    request_deserializer=analytics__pb2.GetUserAbilityRequest.FromString,
                    response_serializer=analytics__pb2.GetUserAbilityResponse.SerializeToString,
            ),
            'GetNextAdaptiveQuestion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNextAdaptiveQuestion,
                    request_deserializer=analytics__pb2.GetNextAdaptiveQuestionRequest.FromString,
                    response_serializer=analytics__pb2.GetNextAdaptiveQuestionResponse.SerializeToString,
            ),
            'UpdateBkt': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBkt,
                    request_deserializer=analytics__pb2.UpdateBktRequest.FromString,
                    response_serializer=analytics__pb2.UpdateBktResponse.SerializeToString,
            ),
            'GetUserLearningSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserLearningSummary,
                    request_deserializer=analytics__pb2.GetUserLearningSummaryRequest.FromString,
                    response_serializer=analytics__pb2.UserLearningSummaryResponse.SerializeToString,
            ),
            'GetGoalAnalytics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGoalAnalytics,
                    request_deserializer=analytics__pb2.GetGoalAnalyticsRequest.FromString,
                    response_serializer=analytics__pb2.LearningGoalAnalyticsResponse.SerializeToString,
            ),
            'GetCourseStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCourseStatistics,
                    request_deserializer=analytics__pb2.GetCourseStatisticsRequest.FromString,
                    response_serializer=analytics__pb2.CourseStatsResultResponse.SerializeToString,
            ),
            'GetLearningPathStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLearningPathStatistics,
                    request_deserializer=analytics__pb2.GetLearningPathStatisticsRequest.FromString,
                    response_serializer=analytics__pb2.LearningPathStatsResultResponse.SerializeToString,
            ),
            'GetDetailedLearningAnalytics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDetailedLearningAnalytics,
                    request_deserializer=analytics__pb2.GetDetailedLearningAnalyticsRequest.FromString,
                    response_serializer=analytics__pb2.GetDetailedLearningAnalyticsResponse.SerializeToString,
            ),
            'CalculateCourseProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateCourseProgress,
                    request_deserializer=analytics__pb2.CalculateCourseProgressRequest.FromString,
                    response_serializer=analytics__pb2.CourseProgress.SerializeToString,
            ),
            'GetUserDataForProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserDataForProfile,
                    request_deserializer=analytics__pb2.GetUserDataForProfileRequest.FromString,
                    response_serializer=analytics__pb2.GetUserDataForProfileResponse.SerializeToString,
            ),
            'GetFilteredRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFilteredRecommendations,
                    request_deserializer=analytics__pb2.GetFilteredRecommendationsRequest.FromString,
                    response_serializer=analytics__pb2.GetFilteredRecommendationsResponse.SerializeToString,
            ),
            'GetUserFeatureVector': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserFeatureVector,
                    request_deserializer=analytics__pb2.GetUserFeatureVectorRequest.FromString,
                    response_serializer=analytics__pb2.GetUserFeatureVectorResponse.SerializeToString,
            ),
            'UpdateBktSkillMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBktSkillMetrics,
                    request_deserializer=analytics__pb2.UpdateBktSkillMetricsRequest.FromString,
                    response_serializer=analytics__pb2.UpdateBktSkillMetricsResponse.SerializeToString,
            ),
            'BatchTrackEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchTrackEvents,
                    request_deserializer=analytics__pb2.BatchEventRequest.FromString,
                    response_serializer=analytics__pb2.BatchEventResponse.SerializeToString,
            ),
            'GetCollaborativeRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollaborativeRecommendations,
                    request_deserializer=analytics__pb2.CollaborativeRecommendationRequest.FromString,
                    response_serializer=analytics__pb2.CollaborativeRecommendationResponse.SerializeToString,
            ),
            'GetTrendingPaths': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrendingPaths,
                    request_deserializer=analytics__pb2.TrendingPathsRequest.FromString,
                    response_serializer=analytics__pb2.TrendingPathsResponse.SerializeToString,
            ),
            'GetPathAnalytics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPathAnalytics,
                    request_deserializer=analytics__pb2.PathAnalyticsRequest.FromString,
                    response_serializer=analytics__pb2.PathAnalyticsResponse.SerializeToString,
            ),
            'GetCohortAnalytics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCohortAnalytics,
                    request_deserializer=analytics__pb2.GetCohortAnalyticsRequest.FromString,
                    response_serializer=analytics__pb2.CohortAnalyticsResponse.SerializeToString,
            ),
            'GetQuizAttemptHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQuizAttemptHistory,
                    request_deserializer=analytics__pb2.QuizAttemptHistoryRequest.FromString,
                    response_serializer=analytics__pb2.QuizAttemptHistoryResponse.SerializeToString,
            ),
            'GetRelatedResources': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRelatedResources,
                    request_deserializer=analytics__pb2.RelatedResourcesRequest.FromString,
                    response_serializer=analytics__pb2.RelatedResourcesResponse.SerializeToString,
            ),
            'GenerateStudyRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateStudyRecommendations,
                    request_deserializer=analytics__pb2.StudyRecommendationsRequest.FromString,
                    response_serializer=analytics__pb2.StudyRecommendationsResponse.SerializeToString,
            ),
            'GenerateNextSteps': grpc.unary_unary_rpc_method_handler(
                    servicer.GenerateNextSteps,
                    request_deserializer=analytics__pb2.NextStepsRequest.FromString,
                    response_serializer=analytics__pb2.NextStepsResponse.SerializeToString,
            ),
            'PredictBKT': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictBKT,
                    request_deserializer=analytics__pb2.PredictBKTRequest.FromString,
                    response_serializer=analytics__pb2.PredictBKTResponse.SerializeToString,
            ),
            'PredictBurnModel': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictBurnModel,
                    request_deserializer=analytics__pb2.PredictBurnRequest.FromString,
                    response_serializer=analytics__pb2.PredictBurnResponse.SerializeToString,
            ),
            'GetFocusRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFocusRecommendations,
                    request_deserializer=analytics__pb2.GetFocusRecommendationsRequest.FromString,
                    response_serializer=analytics__pb2.GetFocusRecommendationsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analytics.AnalyticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('analytics.AnalyticsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalyticsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetHealth',
            analytics__pb2.HealthRequest.SerializeToString,
            analytics__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictPerformance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/PredictPerformance',
            analytics__pb2.PredictPerformanceRequest.SerializeToString,
            analytics__pb2.PredictPerformanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEngagementMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetEngagementMetrics',
            analytics__pb2.GetEngagementMetricsRequest.SerializeToString,
            analytics__pb2.GetEngagementMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetRecommendations',
            analytics__pb2.GetRecommendationsRequest.SerializeToString,
            analytics__pb2.GetRecommendationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateAttemptMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/UpdateAttemptMetrics',
            analytics__pb2.AttemptMetricsRequest.SerializeToString,
            analytics__pb2.UpdateAttemptMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserAbility(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetUserAbility',
            analytics__pb2.GetUserAbilityRequest.SerializeToString,
            analytics__pb2.GetUserAbilityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNextAdaptiveQuestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetNextAdaptiveQuestion',
            analytics__pb2.GetNextAdaptiveQuestionRequest.SerializeToString,
            analytics__pb2.GetNextAdaptiveQuestionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBkt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/UpdateBkt',
            analytics__pb2.UpdateBktRequest.SerializeToString,
            analytics__pb2.UpdateBktResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserLearningSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetUserLearningSummary',
            analytics__pb2.GetUserLearningSummaryRequest.SerializeToString,
            analytics__pb2.UserLearningSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGoalAnalytics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetGoalAnalytics',
            analytics__pb2.GetGoalAnalyticsRequest.SerializeToString,
            analytics__pb2.LearningGoalAnalyticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCourseStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetCourseStatistics',
            analytics__pb2.GetCourseStatisticsRequest.SerializeToString,
            analytics__pb2.CourseStatsResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetLearningPathStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetLearningPathStatistics',
            analytics__pb2.GetLearningPathStatisticsRequest.SerializeToString,
            analytics__pb2.LearningPathStatsResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetDetailedLearningAnalytics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetDetailedLearningAnalytics',
            analytics__pb2.GetDetailedLearningAnalyticsRequest.SerializeToString,
            analytics__pb2.GetDetailedLearningAnalyticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateCourseProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/CalculateCourseProgress',
            analytics__pb2.CalculateCourseProgressRequest.SerializeToString,
            analytics__pb2.CourseProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserDataForProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetUserDataForProfile',
            analytics__pb2.GetUserDataForProfileRequest.SerializeToString,
            analytics__pb2.GetUserDataForProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFilteredRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetFilteredRecommendations',
            analytics__pb2.GetFilteredRecommendationsRequest.SerializeToString,
            analytics__pb2.GetFilteredRecommendationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserFeatureVector(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetUserFeatureVector',
            analytics__pb2.GetUserFeatureVectorRequest.SerializeToString,
            analytics__pb2.GetUserFeatureVectorResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBktSkillMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/UpdateBktSkillMetrics',
            analytics__pb2.UpdateBktSkillMetricsRequest.SerializeToString,
            analytics__pb2.UpdateBktSkillMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchTrackEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/BatchTrackEvents',
            analytics__pb2.BatchEventRequest.SerializeToString,
            analytics__pb2.BatchEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCollaborativeRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetCollaborativeRecommendations',
            analytics__pb2.CollaborativeRecommendationRequest.SerializeToString,
            analytics__pb2.CollaborativeRecommendationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTrendingPaths(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetTrendingPaths',
            analytics__pb2.TrendingPathsRequest.SerializeToString,
            analytics__pb2.TrendingPathsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPathAnalytics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetPathAnalytics',
            analytics__pb2.PathAnalyticsRequest.SerializeToString,
            analytics__pb2.PathAnalyticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCohortAnalytics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetCohortAnalytics',
            analytics__pb2.GetCohortAnalyticsRequest.SerializeToString,
            analytics__pb2.CohortAnalyticsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQuizAttemptHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetQuizAttemptHistory',
            analytics__pb2.QuizAttemptHistoryRequest.SerializeToString,
            analytics__pb2.QuizAttemptHistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRelatedResources(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetRelatedResources',
            analytics__pb2.RelatedResourcesRequest.SerializeToString,
            analytics__pb2.RelatedResourcesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateStudyRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GenerateStudyRecommendations',
            analytics__pb2.StudyRecommendationsRequest.SerializeToString,
            analytics__pb2.StudyRecommendationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateNextSteps(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GenerateNextSteps',
            analytics__pb2.NextStepsRequest.SerializeToString,
            analytics__pb2.NextStepsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictBKT(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/PredictBKT',
            analytics__pb2.PredictBKTRequest.SerializeToString,
            analytics__pb2.PredictBKTResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictBurnModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/PredictBurnModel',
            analytics__pb2.PredictBurnRequest.SerializeToString,
            analytics__pb2.PredictBurnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFocusRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetFocusRecommendations',
            analytics__pb2.GetFocusRecommendationsRequest.SerializeToString,
            analytics__pb2.GetFocusRecommendationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
