import React from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/shared/components/ui/card';
import { Button } from '@/shared/components/ui/button';
import { Sparkles, TrendingUp, AlertCircle, Zap } from 'lucide-react';
import Link from 'next/link';
import { Progress } from '@/shared/components/ui/progress';

interface AutoGeneratedQuizCardProps {
  quizId: string;
  weaknessTopicName: string;
  oldMastery: number; // 0-1 scale
  riskLevel: 'HIGH' | 'MEDIUM' | 'LOW';
  detectedAt: Date;
  onDismiss?: () => void;
  onStartClick?: () => void;
}

const riskLevelConfig = {
  HIGH: {
    color: 'bg-red-100 border-red-300',
    badge: 'bg-red-500',
    icon: AlertCircle,
    label: 'Critical',
  },
  MEDIUM: {
    color: 'bg-yellow-100 border-yellow-300',
    badge: 'bg-yellow-500',
    icon: Zap,
    label: 'Needs Attention',
  },
  LOW: {
    color: 'bg-blue-100 border-blue-300',
    badge: 'bg-blue-500',
    icon: TrendingUp,
    label: 'Low Priority',
  },
};

export const AutoGeneratedQuizCard: React.FC<AutoGeneratedQuizCardProps> = ({
  quizId,
  weaknessTopicName,
  oldMastery,
  riskLevel,
  detectedAt,
  onDismiss,
  onStartClick,
}) => {
  const config = riskLevelConfig[riskLevel];
  const RiskIcon = config.icon;

  return (
    <Card className={`border-2 ${config.color} relative overflow-hidden`}>
      {/* Decorative background element */}
      <div className="absolute top-0 right-0 opacity-10">
        <Sparkles className="w-20 h-20 text-purple-500" />
      </div>

      <CardHeader className="relative z-10">
        <div className="flex items-start justify-between mb-2">
          <div className="flex items-center gap-2">
            <div className="p-2 bg-linear-to-br from-purple-400 to-purple-600 rounded-lg">
              <Sparkles className="w-4 h-4 text-white" />
            </div>
            <span className={`${config.badge} text-white px-2 py-1 rounded text-sm font-semibold`}>
              {config.label}
            </span>
          </div>
          <RiskIcon className="w-5 h-5 text-current opacity-60" />
        </div>

        <CardTitle className="text-lg font-semibold">
          AI-Generated Practice Quiz
        </CardTitle>
        <CardDescription className="text-sm">
          Custom quiz targeting {weaknessTopicName}
        </CardDescription>
      </CardHeader>

      <CardContent className="relative z-10">
        {/* Weakness details */}
        <div className="mb-4 p-3 bg-white rounded-lg border">
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-sm font-medium text-gray-700">
                Current Mastery
              </span>
              <span className="text-sm font-bold text-gray-900">
                {Math.round(oldMastery * 100)}%
              </span>
            </div>
            <Progress value={oldMastery * 100} className="h-2 bg-slate-100" />
          </div>
          <p className="text-xs text-gray-600 mt-2">
            We detected a weakness in this area. A custom 5-question quiz has been created to help strengthen your understanding.
          </p>
        </div>

        {/* Benefits callout */}
        <div className="mb-4 p-3 bg-linear-to-r from-purple-50 to-blue-50 rounded-lg border border-purple-200">
          <div className="flex gap-2">
            <TrendingUp className="w-4 h-4 text-purple-600 shrink-0 mt-0.5" />
            <div className="text-sm">
              <p className="font-medium text-purple-900">Why take this quiz?</p>
              <ul className="text-xs text-purple-700 mt-1 space-y-1">
                <li>• Targeted questions for {weaknessTopicName}</li>
                <li>• Estimated 5-10 minutes</li>
                <li>• Personalized based on your performance</li>
              </ul>
            </div>
          </div>
        </div>

        {/* Actions */}
        <div className="flex gap-2">
          <Link href={`/quiz/${quizId}`} className="flex-1">
            <Button
              className="w-full bg-linear-to-r from-purple-600 to-purple-700 hover:from-purple-700 hover:to-purple-800"
              onClick={onStartClick}
            >
              Start Quiz Now
            </Button>
          </Link>
          {onDismiss && (
            <Button
              variant="outline"
              onClick={onDismiss}
              className="px-3"
            >
              Later
            </Button>
          )}
        </div>

        {/* Metadata */}
        <p className="text-xs text-gray-500 mt-3 text-center">
          Created {new Date(detectedAt).toLocaleDateString()}
        </p>
      </CardContent>
    </Card>
  );
};

export default AutoGeneratedQuizCard;
