import {
  Controller,
  Get,
  Post,
  Body,
  Param,
  UseGuards,
  Query,
  Request,
  HttpCode,
  HttpStatus,
} from '@nestjs/common';
import { ApiOperation, ApiTags, ApiBearerAuth } from '@nestjs/swagger';
import { QuizService } from '../services/quiz.service';
import { WeaknessOrchestrationService } from '../services/weakness-orchestration.service';
import { JwtAuthGuard } from '#modules/auth/guards/jwt-auth.guard';
import { SubmitQuizDto, SubmitAnswerDto } from '#common/dto/assessment.dto';

@ApiTags('Quiz')
@ApiBearerAuth()
@Controller('quizzes')
@UseGuards(JwtAuthGuard)
export class QuizController {
  constructor(
    private readonly quizService: QuizService,
    private readonly orchestrationService: WeaknessOrchestrationService,
  ) {}

  @Get('unit/:unitId')
  @ApiOperation({ summary: 'Get questions for a unit-based quiz' })
  async getQuestionsByUnit(@Param('unitId') unitId: string) {
    return this.quizService.getQuestionsByUnit(unitId);
  }

  @Get('topic/:topicId')
  @ApiOperation({ summary: 'Get questions for a topic-based quiz' })
  async getQuestionsByTopic(@Param('topicId') topicId: string) {
    return this.quizService.getQuestionsByTopic(topicId);
  }

  @Post('topic/:topicId/submit')
  @HttpCode(HttpStatus.CREATED)
  @ApiOperation({ summary: 'Submit a topic quiz' })
  async submitTopicQuiz(
    @Request() req: any,
    @Param('topicId') topicId: string,
    @Body() body: any,
  ) {
    const userId = req.user.id;
    return this.quizService.submitTopicQuiz(userId, topicId, body.responses || []);
  }

  @Post('unit/:unitId/generate')
  @ApiOperation({ summary: 'Generate a quiz for a unit' })
  async generateUnitQuiz(@Request() req: any, @Param('unitId') unitId: string) {
    return this.quizService.generateUnitQuiz(unitId, req.user.id);
  }

  @Post('submit')
  @HttpCode(HttpStatus.CREATED)
  @ApiOperation({ summary: 'Submit a quiz answer or full quiz' })
  async submit(
    @Request() req: any,
    @Query('type') type: string,
    @Body() body: SubmitQuizDto | SubmitAnswerDto,
  ) {
    const userId = req.user.id;

    if (type === 'full') {
      const { unitId, answers } = body as SubmitQuizDto;
      return this.quizService.submitQuiz(userId, unitId, answers);
    }

    // Default to single answer submission
    const submitDto = body as SubmitAnswerDto;
    const answer = submitDto.answerData
      ? JSON.stringify(submitDto.answerData)
      : submitDto.selectedOptionIds?.[0] || '';

    return this.quizService.submitAnswer(userId, submitDto.questionId, answer);
  }

  @Get('results/:userId/:unitId')
  @ApiOperation({ summary: 'Get quiz results for a user' })
  async getQuizResults(
    @Param('userId') userId: string,
    @Param('unitId') unitId: string,
  ) {
    return this.quizService.getUserQuizResults(userId, unitId);
  }

  @Get('rapid-review/:userId')
  @ApiOperation({ summary: 'Get rapid review questions' })
  async getRapidReviewQuestions(
    @Param('userId') userId: string,
    @Query('topics') topics?: string,
  ) {
    const topicsArray = topics ? topics.split(',') : undefined;
    return this.quizService.getRapidReviewQuestions(userId, topicsArray);
  }

  @Get('assessments/auto-generated-quizzes')
  @ApiOperation({ summary: 'Get pending auto-generated quizzes for user' })
  async getAutoGeneratedQuizzes(@Request() req: any) {
    const userId = req.user.id;
    const quizzes = await this.orchestrationService.getPendingAutoQuizzes(userId);
    return { data: quizzes };
  }

  @Get('analytics/weakness-chains')
  @ApiOperation({ summary: 'Get weakness chains for user' })
  async getWeaknessChains(@Request() req: any) {
    const userId = req.user.id;
    const chains = await this.orchestrationService.getWeaknessChainsForUser(userId);
    return { data: chains };
  }

  @Post('assessments/auto-quiz/complete')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'Record completion of auto-generated quiz' })
  async completeAutoQuiz(
    @Request() req: any,
    @Body() body: { quizId: string; score: number; maxScore: number },
  ) {
    const userId = req.user.id;
    const { quizId, score, maxScore } = body;

    // Emit event for orchestration service to handle improvement tracking
    this.orchestrationService['eventEmitter']?.emit('auto-quiz.completed', {
      userId,
      quizId,
      score,
      maxScore,
      timestamp: new Date(),
    });

    return {
      success: true,
      message: 'Quiz completion recorded',
    };
  }
}
