import { Injectable, Logger } from '@nestjs/common';
import { EventEmitter2, OnEvent } from '@nestjs/event-emitter';
import { PrismaService } from '#infrastructure/prisma/prisma.service';
import { WeaknessChainService } from '#modules/ai-analytics/services/weakness-chain.service';
import { QuizGenerationService, WeaknessChain } from './quiz-generation.service';
import { NotificationsService } from '#modules/engagement-communication/services/notifications.service';

interface AssessmentCompleteEvent {
  userId: string;
  courseId?: string;
  topicId?: string;
  score: number;
  maxScore: number;
  timestamp: Date;
}

interface AutoQuizCompleteEvent {
  userId: string;
  quizId: string;
  score: number;
  maxScore: number;
  timestamp: Date;
}

@Injectable()
export class WeaknessOrchestrationService {
  private readonly logger = new Logger(WeaknessOrchestrationService.name);

  constructor(
    private weaknessChainService: WeaknessChainService,
    private quizGenerationService: QuizGenerationService,
    private notificationService: NotificationsService,
    private prisma: PrismaService,
    private eventEmitter: EventEmitter2,
  ) {}

  /**
   * Main orchestration: Listen for assessment completion
   * Detect weakness → Auto-generate quiz → Notify user
   */
  @OnEvent('assessment.completed', { async: true })
  async onAssessmentComplete(event: AssessmentCompleteEvent): Promise<void> {
    try {
      const { userId } = event;

      this.logger.log(`Running weakness detection for user ${userId}`);

      // 1. Run weakness detection for user
      const weaknessChains =
        await this.weaknessChainService.detectWeaknessChains(userId);

      if (weaknessChains.length === 0) {
        this.logger.debug(`No weaknesses detected for user ${userId}`);
        return;
      }

      this.logger.log(
        `Detected ${weaknessChains.length} weaknesses for user ${userId}`,
      );

      // 2. For each HIGH/MEDIUM weakness, generate quiz
      for (const chain of weaknessChains.filter(c => c.riskLevel !== 'LOW')) {
        try {
          const quiz = await this.quizGenerationService.generateQuizForWeakness(
            userId,
            chain,
            5, // 5 questions
          );

          // 3. Notify user
          await this.notificationService.create(
            userId,
            `We created a custom 5-question quiz to help strengthen this area. Your current mastery: ${(chain.weakTopic.pKnown * 100).toFixed(0)}%`,
            'WEAKNESS_QUIZ',
            {
              title: `AI Detected Weakness in ${chain.weakTopic.name}`,
              actionUrl: `/quiz/${quiz.id}`,
            },
            'important',
          );

          // 4. Store relationship for tracking
          await this.prisma.autoGeneratedQuiz.create({
            data: {
              userId,
              quizId: quiz.id,
              weaknessTopicId: chain.weakTopic.id,
              detectedAt: new Date(),
              riskLevel: chain.riskLevel,
            },
          });

          this.logger.log(
            `Created auto-quiz ${quiz.id} for user ${userId} targeting ${chain.weakTopic.name}`,
          );
        } catch (error) {
          this.logger.error(
            `Failed to generate quiz for weakness ${chain.weakTopic.id}: ${error instanceof Error ? error.message : String(error)}`,
          );
          // Continue with next weakness even if this one fails
        }
      }
    } catch (error) {
      this.logger.error(
        `Error in onAssessmentComplete: ${error instanceof Error ? error.message : String(error)}`,
        error instanceof Error ? error.stack : undefined,
      );
    }
  }

  /**
   * After user completes auto-generated quiz:
   * Track improvement in UserSkillState + send feedback
   */
  @OnEvent('auto-quiz.completed', { async: true })
  async onAutoQuizComplete(event: AutoQuizCompleteEvent): Promise<void> {
    try {
      const { userId, quizId, score, maxScore } = event;

      // 1. Fetch original weakness data
      const autoQuizRecord = await this.prisma.autoGeneratedQuiz.findUnique({
        where: {
          userId_quizId: { userId, quizId },
        },
        include: {
          topic: true,
        },
      });

      if (!autoQuizRecord) {
        this.logger.warn(
          `No auto-quiz record found for quiz ${quizId}. Skipping feedback.`,
        );
        return;
      }

      // 2. Get old pKnown (before weakness was detected)
      const skillState = await this.prisma.userSkillState.findUnique({
        where: {
          userId_skillId: {
            userId,
            skillId: autoQuizRecord.weaknessTopicId,
          },
        },
      });

      const oldPKnown = skillState?.pKnown ?? 0.5;
      const quizPerformance = score / maxScore; // 0.0 - 1.0
      const improvement = Math.min(quizPerformance * 0.2, 0.3); // Max 30% boost
      const newPKnown = Math.min(oldPKnown + improvement, 1.0);

      // 3. Update AutoGeneratedQuiz with completion data
      await this.prisma.autoGeneratedQuiz.update({
        where: {
          userId_quizId: { userId, quizId },
        },
        data: {
          completedAt: new Date(),
          scoreImprovement: newPKnown - oldPKnown,
        },
      });

      // 4. Send feedback
      const improvementPercent = ((newPKnown - oldPKnown) / oldPKnown) * 100;
      await this.notificationService.create(
        userId,
        `Your mastery of ${autoQuizRecord.topic.name} improved from ${(oldPKnown * 100).toFixed(0)}% to ${(newPKnown * 100).toFixed(0)}%. Improvement: +${improvementPercent.toFixed(0)}%. Keep going!`,
        'MASTERY_IMPROVEMENT',
        {
          title: 'Great Progress!',
          actionUrl: `/progress`,
        },
        'important',
      );

      // 5. Emit event for downstream processing if needed
      this.eventEmitter.emit('weakness.improved', {
        userId,
        topicId: autoQuizRecord.weaknessTopicId,
        oldMastery: oldPKnown,
        newMastery: newPKnown,
      });

      this.logger.log(
        `Recorded completion of auto-quiz ${quizId}. Mastery: ${(oldPKnown * 100).toFixed(0)}% → ${(newPKnown * 100).toFixed(0)}%`,
      );
    } catch (error) {
      this.logger.error(
        `Error in onAutoQuizComplete: ${error instanceof Error ? error.message : String(error)}`,
        error instanceof Error ? error.stack : undefined,
      );
    }
  }

  /**
   * Get list of pending auto-generated quizzes for a user
   */
  async getPendingAutoQuizzes(userId: string) {
    const pending = await this.prisma.autoGeneratedQuiz.findMany({
      where: {
        userId,
        completedAt: null,
      },
      include: {
        quiz: {
          select: {
            id: true,
            title: true,
            questionCount: true,
          },
        },
        topic: {
          select: {
            id: true,
            name: true,
          },
        },
      },
      orderBy: {
        detectedAt: 'desc',
      },
    });

    return pending.map((p: any) => ({
      id: p.id,
      quizId: p.quiz.id,
      quizTitle: p.quiz.title,
      weaknessTopicId: p.topic.id,
      weaknessTopicName: p.topic.name,
      riskLevel: p.riskLevel,
      detectedAt: p.detectedAt,
    }));
  }

  /**
   * Get weakness chains for user (for progress dashboard)
   */
  async getWeaknessChainsForUser(userId: string): Promise<WeaknessChain[]> {
    return this.weaknessChainService.detectWeaknessChains(userId);
  }
}
