'use client';

import { useEffect } from 'react';
import { useSession } from 'next-auth/react';
import { useQueryClient } from '@tanstack/react-query';
import { offlineService } from './offlineService';
import { syncService } from './syncService';

export function OfflineSessionManager() {
  const { data: session, status } = useSession();
  const queryClient = useQueryClient();
  const userId = session?.user?.id;

  useEffect(() => {
    if (status !== 'authenticated' || !userId) return;

    let active = true;
    const activateUser = async () => {
      const previousUserId = offlineService.getActiveOfflineUserId();
      if (previousUserId && previousUserId !== userId) {
        try {
          await offlineService.clearUserOfflineContent(previousUserId);
        } catch (error) {
          console.error('[OfflineCache] Could not clear the previous user’s offline cache:', error);
          if (active) offlineService.setActiveOfflineUserId(userId);
          return;
        }
      }
      if (active) offlineService.setActiveOfflineUserId(userId);
    };
    void activateUser().catch(error => {
      console.error('[OfflineCache] Could not prepare the current user’s offline cache:', error);
    });

    return () => {
      active = false;
    };
  }, [status, userId]);

  useEffect(() => {
    if (status !== 'authenticated' || !userId) return;
    const refreshLearningData = () => {
      void Promise.all([
        queryClient.invalidateQueries({ queryKey: ['userProgress', userId] }),
        queryClient.invalidateQueries({ queryKey: ['userLearningStreak', userId] }),
        queryClient.invalidateQueries({ queryKey: ['studyPlanner', userId] }),
        queryClient.invalidateQueries({ queryKey: ['course-progress-dashboard', userId] }),
        queryClient.invalidateQueries({ queryKey: ['courseStatistics', userId] }),
        queryClient.invalidateQueries({ queryKey: ['dashboardAssessmentSummary', userId] }),
        queryClient.invalidateQueries({ queryKey: ['autoGeneratedQuizzes', userId] }),
        queryClient.invalidateQueries({ queryKey: ['studyResume', userId] }),
        queryClient.invalidateQueries({ queryKey: ['courses'] }),
        queryClient.invalidateQueries({ queryKey: ['unit'] }),
      ]).catch(error => {
        console.error('[OfflineSync] Failed to refresh learning data after sync:', error);
      });
    };
    window.addEventListener('learning:offline-sync-complete', refreshLearningData);
    const syncWhenOnline = () => {
      void syncService.syncOutbox().catch(error => {
        console.error('[OfflineSync] Failed to flush queued study activity:', error);
      });
    };
    window.addEventListener('online', syncWhenOnline);
    if (navigator.onLine) syncWhenOnline();
    return () => {
      window.removeEventListener('learning:offline-sync-complete', refreshLearningData);
      window.removeEventListener('online', syncWhenOnline);
    };
  }, [queryClient, status, userId]);

  return null;
}
