import { Role } from '@/shared/enums/role.enum';

export const navigationPermissions = {
  [Role.admin]: [
    'dashboard',
    'courses',
    'learning-paths',
    'ai-tutor',
    'study-planner',
    'progress-tracking',
    'certifications',
    'community',
    'admin-settings',
    'admin-dashboard',
    'instructor-dashboard',
    'community-moderation',
    'profile',
  ],
  [Role.instructor]: [
    'dashboard',
    'courses',
    'learning-paths',
    'ai-tutor',
    'study-planner',
    'progress-tracking',
    'certifications',
    'community',
    'instructor-dashboard',
    'profile',
  ],
  [Role.student]: [
    'dashboard',
    'courses',
    'learning-paths',
    'study-planner',
    'progress-tracking',
    'certifications',
    'community',
    'profile',
  ],
  [Role.moderator]: [
    'dashboard',
    'courses',
    'learning-paths',
    'ai-tutor',
    'study-planner',
    'progress-tracking',
    'certifications',
    'community',
    'community-moderation',
    'profile',
  ],
  [Role.guest]: ['courses', 'community'],
};
